### ISSUE TITLE
Single switch, supported?

### ISSUE THREAD

**Issue by dcaccount** [ilcato/homebridge-Fibaro-HC2#100]
Hello,
First of all congratulations for your great package.

I have just bought a Fibaro single switch and I would like to connect it via Bluetooth to my Raspberry Homebridge server.

Is there a way using your plugin? It would be very useful for those who have to hide the switch in an aerea not covered by the Bluetooth of the Apple TV and the raspberry could act as a repeater or as a bridge.

Should you need any test, please let me know.

Thanks in advance,
Dan

**Comment by ilcato** [comment]
The plugin is for connecting a Fibaro Home Center (2 or light) to HomeKit clients. It supports the Fibaro single switch the z-wave version. Your use case is not covered and cannot easily be implemented.
