### ISSUE TITLE
fibaro linked device for thermostat

### ISSUE THREAD

**Issue by meme1981** [ilcato/homebridge-Fibaro-HC2#101]
hi,
in my fibaro hc2 I use linked device as thermostat,
there's any possibilities to have temperature sensors as thermostat to use them as in Fibaro?
thanks

**Comment by ilcato** [comment]
Can you clarify please?

**Comment by meme1981** [comment]
ok, i use a temperature sensor linked in panel linked devices , in my phone app the temperature sensor change from temperature sensor to danfoss.
if I put in shadows.js  case "com.fibaro.temperatureSensor": 
controlService = new hapService.Thermostat(device.name); ecc... homekit see temperature sensor as thermostat and i can change the value in fibaro but it's always in heat, i can't stop, so i have (x example) heating to 10° while home temperature is 20.

thankyou

from /api/devices/5:
{"id":5,"name":"CUCINA TEMP","roomID":1,"type":"com.fibaro.temperatureSensor","baseType":"com.fibaro.multilevelSensor","enabled":true,"visible":true,"isPlugin":false,"parentId":130,"remoteGatewayId":0,"interfaces":["zwave"],"properties":{"parameters":[{"id":1,"lastReportedValue":10,"lastSetValue":10,"size":1,"value":10},

from /api/mobile/interface/refreshStates?last=5

,{"id":5,"type":"com.fibaro.thermostatSetpoint","log":"","logTemp":"","value":"17.99"},
when i change Temp fromapp:

{"status":"IDLE","last":2280445,"date":"13:29 | 18.5.2018","timestamp":1526642942,"events":[{"type":"DeviceModifiedEvent","data":{"id":769}},{"type":"UpdateReadyEvent","data":{"isReady":false}},{"type":"WizardStepStateChangedEvent","data":{"stepId":"update","value":"done"}},{"type":"MinuteTimerEvent","data":{"time":"2018.05.18 13:29","timestamp":1526642940}},{"type":"HeatingZoneTargetLevelEvent","data":{"id":2}}],"changes":[{"id":1,"type":"com.fibaro.zwavePrimaryController","sunriseHour":"06:00","sunsetHour":"20:53"},

![image](https://user-images.githubusercontent.com/33134595/40232607-c5d215c8-5a9f-11e8-94ce-3759a8110032.png)

**Comment by meme1981** [comment]
italiano: 
per impostare il riscaldamento io ho fatto un linked device tra un attuatore e una sonda di temperatura e l'ho associato a una stanza; da quel momento sulla app fibaro non vedo piu' la sonda di temperatura ma il controllo termostato. quando lo importo in homekit pero' viene vista come sonda di temperatura.

english:
 to set up the heating, I made a linked device between an actor and a temperature sensor and I associated it to a room; from that moment on the fibaro-app  I no longer see the temperature sensor but the thermostat control. when the amount in the homekit is however seen as a temperature probe.

**Comment by ilcato** [comment]
I tried to create a linked device similarly to your setup but the temperature sensor remain a sensor and I don't see a thermostat. How does it work?

**Comment by meme1981** [comment]
to me too, to use it as thermostat i put temperature sensor as thermostat in shadows.js, so it can work as thermostat.but it's always inheriting mode

**Comment by ilcato** [comment]
but remaining in Home Center: how do you use the linked device?

**Comment by meme1981** [comment]
if i from iphone modify temperature it work perfectly but iphone don't take data from fibaro
so it's always in heating

**Comment by ilcato** [comment]
From the native Fibaro app?

**Comment by ilcato** [comment]
Forget the homekit stuff for a moment.
In my understanding a linked device in Home Center  is only manageable from the heating panel (or other panels).
Your are saying that "SALA temp" is a temperature sensor that after linking it to a switch became a thermostat visible as a device in the Fibaro UI in place of the temperature sensor?
This is not happening to me when I setup a linked device like in your case.
Which products do you have (Home Center, version, ...).

**Comment by ilcato** [comment]
Contact me directly so we can setup a call to better understand the issue.

**Comment by meme1981** [comment]
SALA Temp is a fgms-001 if you have a private mail i send to you the access to control directly in fibaro and in homebridge

**Comment by ilcato** [comment]
As discussed directly the current Fibaro API doesn't allow the control of linked devices.

**Comment by grapestech** [comment]
Hello! 

First, thanks for providing such a plugin. 

So basically I have been trying to understand how to add a "Virtual Thermostat" to the iOS home app in order to control heating or cooling devices.  Usually this is done in Fibaro via linked devices (a sensor + a relay) which will appear in the Fibaro mobile app as a virtual thermostat. 

The question : Is there a way to accomplish the above without having a physical thermostat unit?

Thanks.
