### ISSUE TITLE
HomeKit changes operation to Heat when changing temperature

### ISSUE THREAD

**Issue by josecarlosmoimaz** [ilcato/homebridge-Fibaro-HC2#103]
Hi ilcato, firstly thank you very much for all your work. When I change the temperature on HomeKit app the Fibaro HC2 is setting the operation to heat, and because of that the AC does not receive the command. There are two places to change the operation mode on HC2, one that is a mode dedicated virtual device and another in the same virtual device with temperature set. I think the home bridge should keep the operation mode as the same if the AC were turned on.

**Comment by ilcato** [comment]
Which device are you using?

**Comment by josecarlosmoimaz** [comment]
The Remotec ZXT-120, sorry I forgot to mention hehe

**Comment by ilcato** [comment]
@josecarlosmoimaz, this is a wrong behaviour of the API that when you change the temperature it will reset the mode to heat, and this parameter is independent from the mode widget. I implemented a workaround that seems to work: before setting the temperature store the current mode and after setting the temperature restore the mode.
Have a try.

**Comment by Mx-Razvan** [comment]
@ilcato - it is working. tested with the HC inerface opened and the rapid change from cool - heat - cool is visible.
Thank you for your work

**Comment by ilcato** [comment]
I just published an update that try to solve a problem related to changing temp -> change mode.

**Comment by josecarlosmoimaz** [comment]
I have just tested, when changing the temperature the homebridge is actually changing the mode from cool to heat, the temp, and after that the mode from heat to cool. The problem is that when changing the mode to heat, what comes next the AC doesn't recieve. The point is not changing the mode, or changing the temperature after the mode. All changes while in heat, the AC doesn't respond.

**Comment by josecarlosmoimaz** [comment]
Try to control an AC that doesn't have heat mode. Here what happens:
when changing the temperature directly from hc2
<img width="1064" alt="screen shot 2018-06-01 at 15 51 36" src="https://user-images.githubusercontent.com/32886134/40858466-bc7236be-65b4-11e8-9bb9-8d4edf59828f.png">
when changing the temperature from HomeKit, the line indicated makes the operation mode slightly change from cool to heat, like the previous version, and than the mode comes back to cool. But the temperature command still doesn't work, I bet that its still trying to heat. try to change the temperature on an AC without heat function.
<img width="1074" alt="screen shot 2018-06-01 at 15 52 47" src="https://user-images.githubusercontent.com/32886134/40859175-3b98e436-65b7-11e8-8da8-823aa5d1e79e.png">
Thanks

**Comment by josecarlosmoimaz** [comment]
@ilcato Oyeah, very nice job. Thats perfect now. Thanks a lot.

**Comment by ilcato** [comment]
@Mx-Razvan, update to 2.1.3. It fixes the issue.
