### ISSUE TITLE
Unable to Autostart with Raspberry pi

### ISSUE THREAD

**Issue by brendanlim1995** [ilcato/homebridge-Fibaro-HC2#104]
Error message when autostart the Homebridge program as below.

> [2018-6-15 13:26:18] [FibaroHC2] didFinishLaunching. 
[2018-6-15 13:26:18] Homebridge is running on port 51824.
[2018-6-15 13:26:19] [FibaroHC2] Error getting data from Home Center:  { Error: connect ENETUNREACH 192.168.1.116:80 - Local (0.0.0.0:0)
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at internalConnect (net.js:934:16)
    at net.js:1029:9
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  code: 'ENETUNREACH',
  errno: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.1.116',
  port: 80 }
(node:798) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Startup error: get scenes or devices
(node:798) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I am using `crontab -e` to Autostart the home bridge program, as the .sh doc as below

> \#!/bin/sh
\# launcher.sh
\# navigate to home directory, then to this directory, then execute python script, then back home
sudo systemctl restart systemd-resolved
sudo systemctl restart homebridge
sudo killall homebridge
sudo python open_homebridge.py

As in the py script:

> import os
os.system("sudo homebridge")

But I can successfully run the `homebridge` from the terminal.
As the `wpa_supplicant` file looks like:

> country=TW
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
        ssid="Network"
        psk="Passwork"
        id_str="AP1"
}

For the `/etc/network/interface`, with AP opened

> auto lo
auto ap0
auto wlan0
iface lo inet loopback
allow-hotplug ap0
iface ap0 inet static
    address 192.168.10.1
    netmask 255.255.255.0
    hostapd /etc/hostapd/hostapd.conf
allow-hotplug wlan0
iface wlan0 inet manual
    wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
iface AP1 inet dhcp

Why did the Error happened, it sometimes will appear the`ENETUNREACH` error message. Is there any way to fix this problems? Thanks Guys.

**Comment by ilcato** [comment]
Use one of the solution described [here](https://github.com/nfarina/homebridge/wiki/Running-Homebridge-on-a-Raspberry-Pi#running-homebridge-on-bootup) in order to autostart homebridge.

**Comment by ilcato** [comment]
@brendanlim1995, any news?

**Comment by brendanlim1995** [comment]
@ilcato 
Thanks, quite busy for the last few days.
Juz follow the step you gave, it works perfectly. Thanks again!

**Comment by brendanlim1995** [comment]
Sorry to say that, the homebridge which autostart successfully yesterday is having a problem again.

<img width="974" alt="screen shot 2018-06-20 at 5 56 30 pm" src="https://user-images.githubusercontent.com/22288227/41651522-56d0f54e-74b3-11e8-8586-3d483586311d.png">

After I delete the paired homebridge on my iPhone and reboot the RPi, I can find the homebridge in my home kit (in iPhone), but it can't be paired again.

What happened to my homebridge again, can someone help me? By the way, the config.json file didn't change at all.

The config.json file looks like below.

<img width="335" alt="screen shot 2018-06-20 at 6 00 36 pm" src="https://user-images.githubusercontent.com/22288227/41651746-de62e4a4-74b3-11e8-95de-05233f479398.png">

The error comes in my iPhone as below.

![img_45e77c919f95-1](https://user-images.githubusercontent.com/22288227/41651980-855b882e-74b4-11e8-804f-b0cb9f90b6b8.jpeg)


Thanks!

**Comment by ilcato** [comment]
delete the accessories folder and the persist folder.
change a number in the username field in the bridge section.
restart

**Comment by ilcato** [comment]
@brendanlim1995, not necessarily, I never reset the platform in more than 12 month even while using it as a test environment. Sometimes homebridge and or plugins corrupt something internally.
Does it work now?

**Comment by brendanlim1995** [comment]
@ilcato 
Yes, it works perfectly right now. I can control my accessories on Fibaro with my iPhone again.
Thanks!

**Comment by brendanlim1995** [comment]
Hi, @ilcato 
the problems came back again, the same problem but I have tried the solution that you gave me about a week ago.
I had changed the Username in homebridge and the port. But it just looked the same.

Any help?
<img width="1159" alt="screen shot 2018-06-26 at 8 54 56 pm" src="https://user-images.githubusercontent.com/22288227/41913681-8ccbaf16-7983-11e8-9e81-ba4f945633fb.png">

**Comment by ilcato** [comment]
ENETUNREACH  means that you are not able to reach the destination address. Does the error happen on startup?

**Comment by ilcato** [comment]
So that means that homebridge starts before the networking subsystem is ready. Try another autostart option that you find in the wiki.

**Comment by brendanlim1995** [comment]
Okay, I will try it later. Thanks a lot

**Comment by brendanlim1995** [comment]
@ilcato I have successfully autostarted the homebridge by using systemctl's pause.
Thanks!
