### ISSUE TITLE
Fibaro HC2: dimming value has no effect

### ISSUE THREAD

**Issue by xPRozAcx** [ilcato/homebridge-Fibaro-HC2#106]
When I set a value in brightness state I get the following debug log, but nothing happens @ Fibaro HC2

`[2018-6-18 12:42:36] [FibaroHC2] Setting value to device: 6 parameter: Brightness 
...
[2018-6-18 12:42:36] [FibaroHC2] Command: setValue, value: 20, to: 6 
[2018-6-18 12:42:37] [FibaroHC2] Updating value for device: 6 parameter: On, value: 20 
[2018-6-18 12:42:37] [FibaroHC2] Updating value for device: 6 parameter: Brightness, value: 20`

**Comment by xPRozAcx** [comment]
It is a FGF212 Dimmer by Fibaro. The same happens to a Domitech dimmable light bulb.

**Comment by ilcato** [comment]
I have a dozen of such things working on my setup. Are other things working on your setup?

**Comment by xPRozAcx** [comment]
Thats what I thought. All other is working like a charme.

**Comment by ilcato** [comment]
have they ever worked?

**Comment by xPRozAcx** [comment]
No. Never...

**Comment by ilcato** [comment]
Which version of nodejs, homebridge and my plugin do you have ?
On which platform are you running this stuff?

**Comment by ilcato** [comment]
@xPRozAcx, any info?

**Comment by ilcato** [comment]
@xPRozAcx, any info?
