### ISSUE TITLE
RGBW missing white channel

### ISSUE THREAD

**Issue by petehhhhh** [ilcato/homebridge-Fibaro-HC2#107]
Hiya,

I read that RGBW fibaro units are supported, which they are. Only problem is that does not appear to be setting white channel so colours are all off ?

**Comment by ilcato** [comment]
The white channel is indeed supported. Some users made several tests on it. Unfortunately I do not have one and cannot check. What's your setup?

**Comment by petehhhhh** [comment]
I have the latest homebridge-Fibaro-HC2 2.1.5. Running on ubuntu 18.04. It is a fibaro RGBW on an HC2 running latest firmware with a connected RGBW strip. When I try to use Home app, the colours change but are quite a bit off. From what I can see (just playing around with it) it is because of the white channel is not correctly setting...

**Comment by petehhhhh** [comment]
not to worry. Think it is a problem with fibaro too. Colours aren't mapping especially oranges and the like...
