### ISSUE TITLE
Scenes are not triggered when script change Global Var

### ISSUE THREAD

**Issue by nicobode** [ilcato/homebridge-Fibaro-HC2#108]
Hey, 

Scenes are not Triggerd when a global war is changed. Yout must add in your PUT request the information  "invokeScenes": true

Thanks :)

**Comment by nicobode** [comment]
In file fibaro-api.js you have the function setGlobalVariable here you must replace 
                "value": value

with 
                "value": value,
                "invokeScenes": true

Reson is: at the moment your script update the global var from false to true or from true to false but when i have example a grafical szene or a lua in fabio with if -> global var = true then this -> than the scene in fibaro isnt running -> that fibaro now that a user want run a scene fibaro need paramenter invoceScenes 

i don`t no why but it isn`t in dokumentation but try it ;)

**Comment by ilcato** [comment]
Understood.
I prepared all the changes in githb but cannot publish on npm from the office. I will publish it tonight from home. thanks.

**Comment by ilcato** [comment]
@nicobode can you test it?

**Comment by ilcato** [comment]
It works for me.
