### ISSUE TITLE
Stuck on Fetching fibaro home center devices

### ISSUE THREAD

**Issue by NiackBuster** [ilcato/homebridge-Fibaro-HC2#11]
hello Ilcato,

I have since few days ago an error when lauch homebridge.
I run on windows8 + gitCmd + last node 2.14.20  + last homebridge + last homebridge-fibaro-h2 (i did a npm update already on everything), fibaro version 4.080.

![1](https://cloud.githubusercontent.com/assets/15909780/16436125/8f02f9b8-3d9b-11e6-8d05-888094794b98.png)
![2](https://cloud.githubusercontent.com/assets/15909780/16436126/8f1aa234-3d9b-11e6-8a35-b1e948c3d092.png)

I tryed to replace your file index.js https://github.com/ilcato/homebridge-Fibaro-HC2/issues/10 and reboot  , i thought it was the same issue as the french guy in #10 but seems not..

I deleted both accessories and persist, tryied to relaunch many times, those files are still empty.

I tryed to uninstall homebridge-fibaro-h2 and modify .json as expected it's launching well.

I'm stuck with no more ideas...

thank you for the work and hope you will help me :)

**Comment by ilcato** [comment]
What's the problem? Are you not able to see the devices in an Homekit app?

**Comment by NiackBuster** [comment]
Yes, and usally the code is at the end, there is no "Fetching  fibaro home center devices"

**Comment by NiackBuster** [comment]
I can see the bridge in homeKit click on it butnothing more after 1mn i get and error "Error  / Echec du réseau ou d'une communication" - EN : "Error, communication or network failed"

usally in homebrige, the 8 digits code was the last thing written in the terminal isn't it ?

**Comment by ilcato** [comment]
It is ok to have the code in that place. It appears at the end only when you delete accessories cache.
Try the following:

- remove accessories and persist folders
- modify the username in config.json (use :61 instead of :6F for example)
- on your iOs device reset the Homekit DB
- restart homebridge

**Comment by NiackBuster** [comment]
I get the exact same issue and screenshots

**Comment by ilcato** [comment]
Which version of iOS do you have?

**Comment by NiackBuster** [comment]
9.3 on iPhone
9.3.2 on iPad

Both same result

2016-06-29 12:12 GMT+02:00 ilcato <notifications@github.com>:

> Which version of iOS do you have?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ilcato/homebridge-Fibaro-HC2/issues/11#issuecomment-229315498>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APLDlCws9DYiLx1Lm9HdtGJZiK3wF758ks5qQkT7gaJpZM4JApqr>
> .
>



--

**Comment by ilcato** [comment]
What errors suggested you to reinstall homebridge?

**Comment by NiackBuster** [comment]
I re installed HomeKit also on the iPad, i had sync pb so i hard-reset the
ipad and re-install a clean HomeKit.
Home bridge was stuck, so I uninstalled all npm modules and installed
again...

2016-06-29 12:16 GMT+02:00 ilcato <notifications@github.com>:

> What errors suggested you to reinstall homebridge?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ilcato/homebridge-Fibaro-HC2/issues/11#issuecomment-229316391>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APLDlDmP8Ai6qKYbmq1KVBWEuuKhuA_pks5qQkYNgaJpZM4JApqr>
> .
>



--

**Comment by ilcato** [comment]
try to logout from iCloud and connect to homebridge

**Comment by NiackBuster** [comment]
I did, I see the bridge click on it but nothing happen until the Error of
communication and network

2016-06-29 12:21 GMT+02:00 ilcato <notifications@github.com>:

> try to logout from iCloud and connect to homebridge
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ilcato/homebridge-Fibaro-HC2/issues/11#issuecomment-229317306>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APLDlO04RjTpvnTOWkYbUT5fKtMDAC5Eks5qQkcpgaJpZM4JApqr>
> .
>



--

**Comment by ilcato** [comment]
I see that you are also using harmony plugin and other accessories. Keep only the fiber plugin and try again.

**Comment by NiackBuster** [comment]
Hi,

I don't understand such a thing :
I uninstalled harmony-hub and http, same result on iPhone and iPad (no
accessory found)
I re installed harmony-hub and http and UNinstalled fibaro-homecenter and
exact same result...

The only thing who  change with the first case only, is the terminal,
ending by "homebridge runing on port..."
Not in the second case, that' S why i thought the problem was
from fibaro-homecenter-hc2...


Le mercredi 29 juin 2016, ilcato <notifications@github.com> a écrit :

> I see that you are also using harmony plugin and other accessories. Keep
> only the fiber plugin and try again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ilcato/homebridge-Fibaro-HC2/issues/11#issuecomment-229330259>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APLDlGMEDoAzERl2-VBucKKdGhFhwRQoks5qQlemgaJpZM4JApqr>
> .
>


--

**Comment by ilcato** [comment]
did you modify the config.json file during the previous tests? Try with a config file with no plugin at all. Always delete persist and accessories folders and reset homier on iOs before each test.

**Comment by NiackBuster** [comment]
i tryed to delete and uninstall all plugins. I still get this error from
ios (with homekit reset and no access/persist)
I'm wondering if there is something with windows... I have no firewall,
windows activated, i am trying to re install visual studio , don't know if
that will change smth...

2016-06-30 5:38 GMT+02:00 ilcato <notifications@github.com>:

> did you modify the config.json file during the previous tests? Try with a
> config file with no plugin at all. Always delete persist and accessories
> folders and reset homier on iOs before each test.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ilcato/homebridge-Fibaro-HC2/issues/11#issuecomment-229551728>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APLDlM4_Vaht2pE5AAw7mVbj0fdtU1f8ks5qQzpHgaJpZM4JApqr>
> .
>



--

**Comment by ilcato** [comment]
Are you able to try it on another machine? Sometimes routers are responsible for this kind of problems, normally for mDNS protocols, but if you see the bridge it should be correct.

**Comment by NiackBuster** [comment]
I try tonight to install the server on a macbook and keep you posted. Thank
so much you for your support !

2016-06-30 13:18 GMT+02:00 ilcato <notifications@github.com>:

> Are you able to try it on another machine? Sometimes routers are
> responsible for this kind of problems, normally for mDNS protocols, but if
> you see the bridge it should be correct.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ilcato/homebridge-Fibaro-HC2/issues/11#issuecomment-229630738>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APLDlAwsn8X6_6WYhJ9_Y7o0VLmpxZE9ks5qQ6YDgaJpZM4JApqr>
> .
>



--

**Comment by NiackBuster** [comment]
I testes on the MacBook, working well on same network.
I tryed also to repair / reinstall Vistual studio, not changing ...

2016-06-30 13:26 GMT+02:00 Thibaut Oger <thibaut@comeleon.fr>:

> I try tonight to install the server on a macbook and keep you posted.
> Thank so much you for your support !
>
> 2016-06-30 13:18 GMT+02:00 ilcato <notifications@github.com>:
>
>> Are you able to try it on another machine? Sometimes routers are
>> responsible for this kind of problems, normally for mDNS protocols, but if
>> you see the bridge it should be correct.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ilcato/homebridge-Fibaro-HC2/issues/11#issuecomment-229630738>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/APLDlAwsn8X6_6WYhJ9_Y7o0VLmpxZE9ks5qQ6YDgaJpZM4JApqr>
>> .
>>
>
>
>
> --
>
>


--

**Comment by ilcato** [comment]
@NiackBuster : any news?

**Comment by ilcato** [comment]
It seems not a problem of the Fibaro HC 2 plugin.
Closing issue.

**Comment by NiackBuster** [comment]
there were but I re install everything to update all components :)

2016-07-06 19:33 GMT+02:00 ilcato <notifications@github.com>:

> It seems not a problem of the Fibaro HC 2 plugin.
> Closing issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ilcato/homebridge-Fibaro-HC2/issues/11#issuecomment-230846463>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APLDlI4x-y29CjVI9Cs_BNCi42_dCikzks5qS-b3gaJpZM4JApqr>
> .
>



--
