### ISSUE TITLE
Remotec ZXT-120 stays on heating mode

### ISSUE THREAD

**Issue by miroslavpetrov** [ilcato/homebridge-Fibaro-HC2#114]
I have installed the newest version of the plugin 2.1.6 and I have two Remotec ZXT-120 connected to my Home Center 2. The mode of both stays only to heating. I read a previous issue from last year where few people stated this problem but finally got it fixed with the new version. Do you have any suggestions on how to fix this?

**Comment by miroslavpetrov** [comment]
UPDATE: I setup a new homebridge and it works fine. However I cannot fix it on my existing homebridge. I removed the package and installed it again but its still not working....

**Comment by ilcato** [comment]
try to delete accessories folder and restart homebridge.
