### ISSUE TITLE
Limiting device list

### ISSUE THREAD

**Issue by 45clouds** [ilcato/homebridge-Fibaro-HC2#115]
Is it possible to add parameter in configuration file that will allow to limit devices which will appear in Home.app?

When I connect to HC2 I receive a lot of devices but I don't want to control some of them via Home.app interface. It would be nice to have a list of devices (for example by entering their ID) that will be visible in HomeKit.

**Comment by ilcato** [comment]
In the config.json use a new home center identity, in home center create such an identity and assign to it the device that you want to see in HomeKit.

**Comment by josecarlosmoimaz** [comment]
I've done that, also because home bridge gets a bit crazy when adding a lot of devices, such as more than 100 for exemple. Creating a new user with limited number of devices allowed is the better way to solve this issue. And also you can have multiple home bridges with many users as well.
