### ISSUE TITLE
wall plug Type G

### ISSUE THREAD

**Issue by maoten2000** [ilcato/homebridge-Fibaro-HC2#124]
would you please consider to add the new fibaro wall plug type G " FGWPG-111" it doesn't recognized at all or show as accessory in homekit app.

**Comment by ilcato** [comment]
Can you please send me the output of the request to the http://HOME_CENTER_IP/api/devices/ID

Where HOME_CENTER_IP is your Home Center IP address and ID is the Id of the Wall plug.

**Comment by maoten2000** [comment]
[FGWPG-111.zip](https://github.com/ilcato/homebridge-Fibaro-HC2/files/2623368/FGWPG-111.zip)

**Comment by maoten2000** [comment]
working beautifly as intended!
Many thanks.
