### ISSUE TITLE
Fibaro ZXT120 issue

### ISSUE THREAD

**Issue by batalhaca** [ilcato/homebridge-Fibaro-HC2#126]
In my case i have 8 ZXT 120 in the HC2 while imported to Homebridge some funny think happend. Some Thermostate in Homekit the mode and the temperature setpoint are controlling different ZXT120. Example: i had a Bed Room and a Living room while i control the Living Room in Homekit to set Cool in the Living Room but the Bed Room ZXT 120 responded and if i control the Living Room setpoint and Living Room responded correctly.i can confirm that the devices in HC2 are named unique no overlaping.

**Comment by ilcato** [comment]
Will check it.

**Comment by ilcato** [comment]
Can you try expose only one device to Homebridge and see if it works?

**Comment by batalhaca** [comment]
Hi, 

I found that the issue only occurs when Fibaro systems had a few remote gateways. Only the ZXT120 from the remote gateway will have this issue and will be fine if all other ZXT are on the main gateway.

Carlos

**Comment by ilcato** [comment]
can you test now?

**Comment by fjosepose** [comment]
Hi
Same issue for me...didn’t find this issue before now so I already created an new issue https://github.com/ilcato/homebridge-Fibaro-HC2/issues/199

**Comment by baafonso** [comment]
the current release version of this plugin has a bug in file shadows.js. this bug is not present in the source file shadows.ts.

to fix open the console on homebridge and edit the file shadows.js on directory :

/usr/local/lib/node_modules/homebridge-fibaro-hc2/dist/

change:

                    controlService.subtype = (controlService.subtype || device.id + "---") + "-" + t.id;



to:

//                    controlService.subtype = (controlService.subtype || device.id + "---") + "-" + t.id;
                       if (controlService.subtype) {
                                controlService.subtype = controlService.subtype + "-" + t.id;
                        } else {
                                controlService.subtype = device.id + "----" + t.id;
                        }

this fixes the problem.

**Comment by ilcato** [comment]
@baafonso, it should be fixed in 2.3.7

**Comment by baafonso** [comment]
@ilcato , confirmed. you can close this issue...
