### ISSUE TITLE
Security - how the system work

### ISSUE THREAD

**Issue by adamkasprzak** [ilcato/homebridge-Fibaro-HC2#127]
Hi!

I have read the Wiki - 
https://github.com/ilcato/homebridge-Fibaro-HC2/wiki/Fibaro-Security-System-configuration-for-HomeKit for the security system, but I don’t understand how actually the system work - what is the algorithm. Could someone please explain.

After setting the state in home app, the change is set in the Fibaro home center? The fibaro Hcl scene is triggered based on the variable change? There are many steps and I feel that I don’t get the whole picture.

I have a Fibaro Home Center LITE version.

Thanks for more  explanations,
Adam

**Comment by adamkasprzak** [comment]
Currently I run the scene “arm the alarm” manually, when I leave my home. The scene is arming the sensors (doors, motion) and when the alarm is breached when I come back (example - door is opened), the alarm is on and the actions in the alarm panel in HCL are running. I have to put a pass in order to stop the alarm. After successfull stop, the scene “alarm off” is trigged which is turning on the lights etc.. 

What I want to achieve is to do as much from above using home app on the iPhone/iPad.

**Comment by ilcato** [comment]
@adamkasprzak, this is exactly what the Security System do.
I updated the wiki a little. Is it more clear?
