### ISSUE TITLE
Can we do the equipment to automatically allocate rooms?

### ISSUE THREAD

**Issue by 1206403782** [ilcato/homebridge-Fibaro-HC2#128]
When we have a lot of devices in HC2, such as more than 100, we need to distribute the devices one by one to the room in Homekit. Also, when our equipment exceeds 80, after two or three days, the equipment in HomeKit will be down, all the equipment will disappear for no reason, so we have to re-add it.

**Comment by ilcato** [comment]
HomeKit doesn't allow more than 100 devices on a single bridge. You need to filter them in Home Center by using a specific username with access right to n more than 100 Home Center IDs.

**Comment by 1206403782** [comment]
> HomeKit doesn't allow more than 100 devices on a single bridge. You need to filter them in Home Center by using a specific username with access right to n more than 100 Home Center IDs.

Ok, I understand. In addition, can the function of automatically assigning rooms be done?

**Comment by arcy67** [comment]
Hello Ilcato, I tried to compile iOS app with Xcode v 8.3, but Xcode needs to convert to current swift syntax, and after conversion the build fails with 43 errors...

Do you plan to update the project in the future? Or have I made some mistake?
 
I used your app in the past and have been very useful! I Have lots of rooms and devices in HC2.

Thank you very much.

**Comment by ilcato** [comment]
sorry, I do not have plan to upgrade it. no time and. no budget

**Comment by arcy67** [comment]
Grazie, peccato, l’app era molto utile!
Per fortuna ho trovato un vecchio iphone che aveva ancora l’app e me la sono cavata con quello. Ora mi terro’ stretto l’iphone :-)

Grazie, ciao.
