### ISSUE TITLE
Homebridge only works on one device

### ISSUE THREAD

**Issue by nassib92** [ilcato/homebridge-Fibaro-HC2#13]
Hi, I have finally successfully got the homebridge to work with my fibaro system. 

The issue I am having is that I got my ipad to discover it and all went well but when I want to use my iphone to discover it it doesn't show up anymore. Is there a reason for that?

Thanks!

**Comment by ilcato** [comment]
If you want to share the same Homekit accessory between 2 or more iOs devices you need to:

- use the same iCloud account on the different devices and in Homekit setting on all devices select "Use iCloud" switch

or with different iCloud account:

- invite the second one from the first one from the Homekit panel setting

**Comment by ilcato** [comment]
@nassib92 : any feedback?

**Comment by nassib92** [comment]
Hi! Yes thanks it worked!

But for some reason I cannot access it remotely or from a different
network. Any idea why?

**Comment by ilcato** [comment]
You must enable explicitly remote access on the iOS devices and you must have an Apple TV 3+ On the same network and with the same iCloud account.

**Comment by ilcato** [comment]
closing
