### ISSUE TITLE
Single Switch not shown in Homebridge

### ISSUE THREAD

**Issue by Deniska93** [ilcato/homebridge-Fibaro-HC2#130]
Hello.

I just got my Raspberry and installed homebridge, which works very well with my Hue Plugin (for Osram lightify plugs) and also well with the Fibaro Plugin for my Roller Shutter. But the plugin does not see my Single Switch. In Homecenter the Single Switch is shown and works, but the Homebridge Plugin just reads out the Roller Shutter. Is there any option I have to configure in Homecenter on the Switch to work with Homebridge Plugin?

Here is the log of Homebridge, no error.

`[12/23/2018, 9:25:15 AM] [FibaroHC2] Initializing FibaroHC2 platform...
[12/23/2018, 9:25:15 AM] Loading 0 accessories...
[12/23/2018, 9:25:15 AM] [FibaroHC2] Configured Accessory:  Rollade-Küche
[12/23/2018, 9:25:15 AM] [FibaroHC2] didFinishLaunching.
[12/23/2018, 9:25:15 AM] [FibaroHC2] Loading accessories
[12/23/2018, 9:25:15 AM] [FibaroHC2] Added/changed accessory:  Rollade-Küche`

Here is a picture of the Switch in Homecenter.
<img width="757" alt="bildschirmfoto 2018-12-23 um 09 37 18" src="https://user-images.githubusercontent.com/25673039/50382039-5e643f80-0696-11e9-94e0-f477e09a4240.png">

**Comment by ilcato** [comment]
Which product is it?

**Comment by Deniska93** [comment]
Fibaro Single Switch

**Comment by ilcato** [comment]
Which specific version? Model number?

**Comment by Deniska93** [comment]
Hey! Sorry for late response, was on holiday. I have a Fibaro Single Switch 2. How to find out the specific Model number?

**Comment by Deniska93** [comment]
Hey, is this what you need?

> {
  "id": 17,
  "name": "Steckdose",
  "roomID": 1,
  "type": "com.fibaro.binarySwitch",
  "baseType": "com.fibaro.actor",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 14,
  "remoteGatewayId": 0,
  "interfaces": [
    "deviceGrouping",
    "energy",
    "light",
    "power",
    "zwave",
    "zwaveMultiChannelAssociation",
    "zwaveProtection"
  ],
  "properties": {
    "parameters": [
      {
        "id": 9,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 10,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 11,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 12,
        "lastReportedValue": 50,
        "lastSetValue": 50,
        "size": 2,
        "value": 50
      },
      {
        "id": 13,
        "lastReportedValue": 5,
        "lastSetValue": 5,
        "size": 2,
        "value": 5
      },
      {
        "id": 20,
        "lastReportedValue": 2,
        "lastSetValue": 2,
        "size": 1,
        "value": 2
      },
      {
        "id": 21,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 27,
        "lastReportedValue": 15,
        "lastSetValue": 15,
        "size": 1,
        "value": 15
      },
      {
        "id": 28,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 29,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 30,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 31,
        "lastReportedValue": 255,
        "lastSetValue": 255,
        "size": 2,
        "value": 255
      },
      {
        "id": 32,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 2,
        "value": 0
      },
      {
        "id": 33,
        "lastReportedValue": 99,
        "lastSetValue": 99,
        "size": 2,
        "value": 99
      },
      {
        "id": 35,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 36,
        "lastReportedValue": 255,
        "lastSetValue": 255,
        "size": 2,
        "value": 255
      },
      {
        "id": 37,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 2,
        "value": 0
      },
      {
        "id": 38,
        "lastReportedValue": 99,
        "lastSetValue": 99,
        "size": 2,
        "value": 99
      },
      {
        "id": 40,
        "lastReportedValue": 3,
        "lastSetValue": 3,
        "size": 1,
        "value": 3
      },
      {
        "id": 41,
        "lastReportedValue": 2,
        "lastSetValue": 2,
        "size": 1,
        "value": 2
      },
      {
        "id": 42,
        "lastReportedValue": 3,
        "lastSetValue": 3,
        "size": 1,
        "value": 3
      },
      {
        "id": 43,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 44,
        "lastReportedValue": 600,
        "lastSetValue": 600,
        "size": 2,
        "value": 600
      },
      {
        "id": 50,
        "lastReportedValue": 20,
        "lastSetValue": 20,
        "size": 1,
        "value": 20
      },
      {
        "id": 51,
        "lastReportedValue": 10,
        "lastSetValue": 10,
        "size": 1,
        "value": 10
      },
      {
        "id": 53,
        "lastReportedValue": 100,
        "lastSetValue": 100,
        "size": 2,
        "value": 100
      },
      {
        "id": 58,
        "lastReportedValue": 3600,
        "lastSetValue": 3600,
        "size": 2,
        "value": 3600
      },
      {
        "id": 59,
        "lastReportedValue": 3600,
        "lastSetValue": 3600,
        "size": 2,
        "value": 3600
      },
      {
        "id": 60,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      }
    ],
    "pollingTimeSec": 0,
    "zwaveCompany": "Fibargroup",
    "zwaveInfo": "3,4,24",
    "zwaveVersion": "3.3",
    "RFProtectionState": "0",
    "RFProtectionSupport": "3",
    "configured": true,
    "dead": "false",
    "deadReason": "",
    "deviceControlType": "2",
    "deviceGroup": "[]",
    "deviceGroupMaster": "0",
    "deviceIcon": "2",
    "emailNotificationID": "0",
    "emailNotificationType": "0",
    "endPointId": "1",
    "energy": "4.17",
    "isLight": "true",
    "localProtectionState": "0",
    "localProtectionSupport": "5",
    "log": "",
    "logTemp": "",
    "manufacturer": "",
    "markAsDead": "false",
    "model": "",
    "nodeId": "3",
    "parametersTemplate": "779",
    "power": "0.00",
    "productInfo": "1,15,4,3,16,0,3,3",
    "protectionExclusiveControl": "0",
    "protectionExclusiveControlSupport": "false",
    "protectionState": "0",
    "protectionTimeout": "0",
    "protectionTimeoutSupport": "false",
    "pushNotificationID": "0",
    "pushNotificationType": "0",
    "remoteGatewayId": "0",
    "saveLogs": "true",
    "serialNumber": "h'0000000000007b0e",
    "showEnergy": "true",
    "smsNotificationID": "0",
    "smsNotificationType": "0",
    "useTemplate": "true",
    "userDescription": "",
    "value": "false"
  },
  "actions": {
    "reconfigure": 0,
    "reset": 0,
    "turnOff": 0,
    "turnOn": 0
  },
  "created": 1545413368,
  "modified": 1545413368,
  "sortOrder": 3
}

**Comment by ilcato** [comment]
Yes it is.
From here I see that the device is described as "com.fibaro.binarySwitch" that is a supported type bu the plugin.

Are you using for the plugin a specific Home Center user ? Did you assign the correct device visibility for it?

**Comment by Deniska93** [comment]
Ahhhh, big thanks! That was the error! I use a specific User for HomeBridge Login at HomeCenter and this user had no access to the Switch! I changed that and now it works!

Thanks a lot! :-)
