### ISSUE TITLE
Aeon Labs Dimmer seen as switch

### ISSUE THREAD

**Issue by alteum-Fib** [ilcato/homebridge-Fibaro-HC2#134]
Hi,

I have dimmer seen as a switch. Is a dimmer  AEON LABS 1.15

So, in home, not possible to use as dimmer, only as switch.

When I use the "dimmer" slide bar, it toggles off or on, no intermediate state.

Any idea ?

Pascal

**Comment by ilcato** [comment]
Can  you send me the output of the http://HOME_CENTER_IP/docs/devices query for this device?

**Comment by alteum-Fib** [comment]
Hi,

Herewith the API of the specific device with problem

{"id":11,"name":"Spots Led Living","roomID":1,"type":"com.fibaro.multilevelSwitch","baseType":"com.fibaro.binarySwitch","enabled":true,"visible":true,"isPlugin":false,"parentId":10,"remoteGatewayId":0,"interfaces":["deviceGrouping","fibaroFirmwareUpdate","levelChange","light","zwave","zwaveConfiguration","zwaveMultiChannelAssociation","zwaveSceneActivation","zwaveSwitchAll"],"properties":{"parameters":[{"id":1,"lastReportedValue":255,"lastSetValue":255,"size":1,"value":255},{"id":6,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":7,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},{"id":8,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},{"id":9,"lastReportedValue":5,"lastSetValue":5,"size":1,"value":5},{"id":10,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},{"id":11,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},{"id":12,"lastReportedValue":99,"lastSetValue":99,"size":1,"value":99},{"id":13,"lastReportedValue":2,"lastSetValue":2,"size":1,"value":2},{"id":14,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":15,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},{"id":16,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},{"id":17,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":18,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":19,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":20,"lastReportedValue":110,"lastSetValue":110,"size":1,"value":110},{"id":30,"lastReportedValue":3,"lastSetValue":3,"size":1,"value":3},{"id":39,"lastReportedValue":600,"lastSetValue":600,"size":2,"value":600},{"id":41,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0}],"pollingTimeSec":0,"zwaveCompany":"Fibargroup","zwaveInfo":"3,3,52","zwaveVersion":"2.2","categories":"[\"lights\"]","configured":true,"dead":"false","deadReason":"","deviceControlType":"2","deviceGroup":"[]","deviceGroupMaster":"0","deviceIcon":"15","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","firmwareUpdate":"{\"info\":\"\",\"progress\":0,\"status\":\"UpToDate\",\"updateVersion\":\"2.2\"}","isLight":"true","log":"","logTemp":"","manufacturer":"","markAsDead":"true","model":"","nodeId":"4","parametersTemplate":"235","productInfo":"1,15,1,0,16,10,2,2","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","sceneActivation":"0","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","switchAllMode":"SWITCH_ALL_INCLUDED_IN_THE_ALL_ON_ALL_OFF_FUNCTIONALITY","updateVersion":"","useTemplate":"true","userDescription":"","value":"0"},"actions":{"abortUpdate":1,"getParameter":1,"reconfigure":0,"retryUpdate":1,"sceneActivationSet":0,"setParameter":2,"setValue":1,"startLevelDecrease":0,"startLevelIncrease":0,"startUpdate":1,"stopLevelChange":0,"turnOff":0,"turnOn":0,"updateFirmware":1},"created":1549538972,"modified":1549538972,"sortOrder":14}

**Comment by ilcato** [comment]
Found the problem. Fix in the next version. Stay tuned.

**Comment by alteum-Fib** [comment]
Top
