### ISSUE TITLE
The iPhone XS,XR is not adaptation,pls check it out. 

### ISSUE THREAD

**Issue by 1206403782** [ilcato/homebridge-Fibaro-HC2#138]
Homebridge can be added to the homekit, but the device cannot be read.

**Comment by ilcato** [comment]
Please explain.

**Comment by 1206403782** [comment]
> Please explain.

IPhone XR will be stuck in the reading device during the process of adding homebridge. After waiting for a while, you can enter the main interface. The homebridge accessory is gray, and other lights, curtains and other accessories are not displayed. It is normal to use another phone.

**Comment by ilcato** [comment]
Don't have an XR. Which other phone are you using?

**Comment by 1206403782** [comment]
> Don't have an XR. Which other phone are you using?
sorry,iphone Xmax.
When you search for and add Homebridge-fibaro-HC2 with the iphone Xmax, it takes a long time to load, and then all the device comes out, but they all out of control. In addition, an iphone8 that normally uses homekit,when it invites iphoneXmax as a family member. The original iphone8 will be demoted from an administrator to an ordinary member, but iphone Xmax still cannot control the homekit device.

**Comment by ilcato** [comment]
Which version of iOs is installed on the Xmax?

**Comment by 1206403782** [comment]
The latest stable version 12.1.4, not bate. As long as it is IOS12 should be the same? How do we know the changes that Homekit has made in different versions?

**Comment by ilcato** [comment]
Is the iphone8 also using 12.1.4 ?

**Comment by 1206403782** [comment]
Yes

**Comment by ilcato** [comment]
I don't think is something related to the specific phone version.
Can you try using another app to add the homebridge to the phone (e.g.: Eve app) ?

**Comment by ilcato** [comment]
@1206403782, did you try another app?
