### ISSUE TITLE
99% brightness shown, when light is 100% on

### ISSUE THREAD

**Issue by dgburton** [ilcato/homebridge-Fibaro-HC2#14]
Thanks for your work on this plugin - great stuff :-)

In iOS 10, using the new Apple Home app, when lights, or blinds are 100% in he HC2 web interface, they are shown in Homekit as 99%.

![img_3324](https://cloud.githubusercontent.com/assets/6538860/16715193/730c2ace-46d1-11e6-9974-0478a2caf659.PNG)

**Comment by ilcato** [comment]
It's only a problem of values range: Fibaro Home center returns 99 when a dimmer (or blind) is at the maximum level instead of 100. I will adjust it.

**Comment by ilcato** [comment]
@dgburton:  are you available to test the [fix](https://raw.githubusercontent.com/ilcato/homebridge-Fibaro-HC2/master/index.js) ?

**Comment by dgburton** [comment]
Sorry for the late reply! I'll test that fix later today @ilcato...

**Comment by dgburton** [comment]
@ilcato:

The "fromFibaro" updates seem to work fine - i.e. it is set to 100% whenever an update comes from the HC2 - i.e. if you change the brightness on the HC2 interface to 100% it now sets it to 100% in Homekit.

However... if you kill and restart Homebridge any Dimmer that was 100% is now set to 99%...

**Comment by ilcato** [comment]
With the last commit it should also work for this case.
Can you test it?

**Comment by dgburton** [comment]
Confirmed fixed. Thanks @ilcato 

I'll close this issue.
