### ISSUE TITLE
Roller Shutter 3 not appearing

### ISSUE THREAD

**Issue by saschaspeidel** [ilcato/homebridge-Fibaro-HC2#141]
Hi there,

I just updated to v2.2 with no success in seeing my roller shutter 3.
What can I do to help making that work?

Regards
Sascha

**Comment by ilcato** [comment]
Can you send me the json file corresponding to it? Use http://HC_IP/docs

**Comment by saschaspeidel** [comment]
Sure. Here‘s the json:

{
  "id": 184,
  "name": "Markise",
  "roomID": 13,
  "type": "com.fibaro.FGR223",
  "baseType": "com.fibaro.FGR",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 181,
  "remoteGatewayId": 0,
  "interfaces": [
    "energy",
    "levelChange",
    "power",
    "zwave",
    "zwaveAlarm",
    "zwaveMultiChannelAssociation",
    "zwaveProtection"
  ],
  "properties": {
    "parameters": [
      {
        "id": 20,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 24,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 25,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 30,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 4,
        "value": 0
      },
      {
        "id": 31,
        "lastReportedValue": 100597760,
        "lastSetValue": 100597760,
        "size": 4,
        "value": 100597760
      },
      {
        "id": 32,
        "lastReportedValue": 33488897,
        "lastSetValue": 33488897,
        "size": 4,
        "value": 33488897
      },
      {
        "id": 33,
        "lastReportedValue": 50266113,
        "lastSetValue": 50266113,
        "size": 4,
        "value": 50266113
      },
      {
        "id": 34,
        "lastReportedValue": 83820545,
        "lastSetValue": 83820545,
        "size": 4,
        "value": 83820545
      },
      {
        "id": 40,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 41,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 60,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 61,
        "lastReportedValue": 15,
        "lastSetValue": 15,
        "size": 2,
        "value": 15
      },
      {
        "id": 62,
        "lastReportedValue": 3600,
        "lastSetValue": 3600,
        "size": 2,
        "value": 3600
      },
      {
        "id": 65,
        "lastReportedValue": 10,
        "lastSetValue": 10,
        "size": 2,
        "value": 10
      },
      {
        "id": 66,
        "lastReportedValue": 3600,
        "lastSetValue": 3600,
        "size": 2,
        "value": 3600
      },
      {
        "id": 150,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 151,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 152,
        "lastReportedValue": 150,
        "lastSetValue": 150,
        "size": 4,
        "value": 150
      },
      {
        "id": 153,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 154,
        "lastReportedValue": 10,
        "lastSetValue": 10,
        "size": 2,
        "value": 10
      },
      {
        "id": 155,
        "lastReportedValue": 10,
        "lastSetValue": 10,
        "size": 2,
        "value": 10
      },
      {
        "id": 156,
        "lastReportedValue": 5825,
        "lastSetValue": 5825,
        "size": 4,
        "value": 5825
      },
      {
        "id": 157,
        "lastReportedValue": 6112,
        "lastSetValue": 6112,
        "size": 4,
        "value": 6112
      }
    ],
    "pollingTimeSec": 0,
    "zwaveCompany": "Fibargroup",
    "zwaveInfo": "3,6,2",
    "zwaveVersion": "5.1",
    "RFProtectionState": "0",
    "RFProtectionSupport": "3",
    "alarmLevel": "0",
    "alarmType": "0",
    "categories": "[\"blinds\"]",
    "configured": true,
    "dead": "false",
    "deadReason": "",
    "deviceControlType": "54",
    "deviceIcon": "87",
    "emailNotificationID": "0",
    "emailNotificationType": "0",
    "endPointId": "1",
    "energy": "0.05",
    "localProtectionState": "0",
    "localProtectionSupport": "5",
    "log": "",
    "logTemp": "",
    "manufacturer": "",
    "markAsDead": "true",
    "model": "",
    "nodeId": "47",
    "parametersTemplate": "822",
    "power": "0.00",
    "productInfo": "1,15,3,3,16,0,5,1",
    "protectionExclusiveControl": "0",
    "protectionExclusiveControlSupport": "false",
    "protectionState": "0",
    "protectionTimeout": "0",
    "protectionTimeoutSupport": "false",
    "pushNotificationID": "0",
    "pushNotificationType": "0",
    "remoteGatewayId": "0",
    "saveLogs": "true",
    "serialNumber": "h'00000000000017eb",
    "showEnergy": "true",
    "smsNotificationID": "0",
    "smsNotificationType": "0",
    "useTemplate": "true",
    "userDescription": "",
    "value": "0",
    "value2": "0"
  },
  "actions": {
    "close": 0,
    "open": 0,
    "reconfigure": 0,
    "reset": 0,
    "setValue": 1,
    "setValue2": 1,
    "startLevelDecrease": 0,
    "startLevelIncrease": 0,
    "stop": 0,
    "stopLevelChange": 0
  },
  "created": 1553354144,
  "modified": 1553354144,
  "sortOrder": 57
}
Response Code
200
PUT /devices/{deviceID} Modify device

**Comment by ilcato** [comment]
Fixed it will be in the next release.

**Comment by saschaspeidel** [comment]
Great! Is there an estimated release date already?

**Comment by ilcato** [comment]
Soon

**Comment by ilcato** [comment]
@saschaspeidel, can you test with the just published 2.2.1 version ?

**Comment by saschaspeidel** [comment]
Unfortunately it‘s still not visible in 2.2.1

**Comment by ilcato** [comment]
@saschaspeidel, my mistake. Try with 2.2.2.

**Comment by saschaspeidel** [comment]
Still not seeing the device. Sorry :-/

**Comment by ilcato** [comment]
Can you send me row number 134 of dist/shadows.js in your installation folder?

**Comment by saschaspeidel** [comment]
135             case "com.fibaro.rollerShutter":
    136                 ss = [new ShadowService(new hapService.WindowCovering(device.name), [hapCharacteristic.CurrentPosition, hapCharacteristic.TargetPosition, hapCharacteristic.PositionState])];
    137                 break;

**Comment by saschaspeidel** [comment]
Sorry sorry sorry. I had multiple installed instances of the npm. Cleaned it up. Look good now...

[FibaroHC2] Added/changed accessory:  Markise

**Comment by ilcato** [comment]
Ok

**Comment by saschaspeidel** [comment]
Again: Sorry. And thanks for developing the fix so quick!
