### ISSUE TITLE
Security System : Stuck on Arming...

### ISSUE THREAD

**Issue by carlittoer** [ilcato/homebridge-Fibaro-HC2#143]
Hi,

When changing the Alarm state (i.e: from Home to Away) the Alarm icon is stuck on Arming... and the state does not change. However In HC2 I can see that the scene has been instantly called. 

Thanks.

**Comment by ilcato** [comment]
Are you using the released version of the plugin or the master's one?

**Comment by carlittoer** [comment]
Hi,

The release with the latest modifications for the danalock.

**Comment by ilcato** [comment]
can you check with the released version?

**Comment by ilcato** [comment]
I have no problem with the current version. Which node.js and iOs do you have?

**Comment by carlittoer** [comment]
I'll try the latest release and let you know.
iOs: 12.3
Node : v9.9.0  (is this fine?)

**Comment by carlittoer** [comment]
Still happening on latest release / node 9.9.0 / iOS 12.3

When you change the status, it is stuck on Arming (with spinner) unless you restart the home app and fetch again the status.

**Comment by ilcato** [comment]
It works in the latest version.

**Comment by carlittoer** [comment]
Hi,

I have the latest. A change in alarm modes works and instantly changes the status in HC2 but the home app status does not change unless you restart it. It shows “Arming...”

Can I help debug?
