### ISSUE TITLE
Last version (2.2.4) duplicate netatmo sensors and deleted devices don't disappear from home app

### ISSUE THREAD

**Issue by redeemer666** [ilcato/homebridge-Fibaro-HC2#151]
Hello ilCato,

your latest version duplicated the temperature and humidity sensors from netatmo plugin (the only different thing is the "model", on one it appear com.fibaro.temperaturesensor and the other one is HomeCenterBridgedAccessory).

Strange thing is, even if I delete these devices from the "homekit" account in home center, they don't disappear from the home app...

Please can you investigate?

**Comment by redeemer666** [comment]
One more thing. The "delete" issue appears on all devices. I have tried to add a device to homekit and it appears correctly, but didn't disappears when deleted from the user account.

**Comment by ilcato** [comment]
@hovorkap,
are you able to manage this cases ?

**Comment by hovorkap** [comment]
I can take a look once I have some spare time. I think correct way to clean a homebridge devices is to remove homebridge hub from the homekit app and then reset the homebridge itself (I use homekit ui and its link on the bottom left of the page). Does this help?

**Comment by redeemer666** [comment]
Hello Hovorkap. Before version 2.2.4 the hc2 plugin removed the devices not anymore "exposed" in the HC2 user just with an homebridge service reboot, please don't ask me to remove the entire hub from home app, I have more than 50 devices connected and divided into 11 rooms, with over 30 homekit automations activated on that devices. Removing the hub means that I have to manually restore all those things.

**Comment by hovorkap** [comment]
Hi @redeemer666,

I finally got some time for investigation. Can you please post or better PM me your "{fibaro ip}/api/devices" json? I will try to init homebridge with older plugin version and then run it with newer one. Maybe homebridge or the plugin has problems with handling devices that change model/manufacturer/whatever. I was not able to reproduce with my current setup (the deletetion of fibaro wall plug was visible in homekit app, so was re-adding)

**Comment by redeemer666** [comment]
Writing you a PM right now

**Comment by redeemer666** [comment]
mmm Can't find a way to PM you. Posting it here (converted to txt because the site can't let me download with original extension)
[devices.txt](https://github.com/ilcato/homebridge-Fibaro-HC2/files/3210644/devices.txt)

**Comment by hovorkap** [comment]
So far I have bad news for you, @redeemer666. I mocked fibaro api with your devices and cannot reproduce the deletion nor the doubling problem.

Steps to reproduce:
1. Install fibaro hc2 plugin v 2.2.3 to homebridge and configure homekit app
outcome: 87 devices found in the homekit app
2. Install fibaro hc2 plugin v 2.2.4 to homebridge and restart homebridge
outcome: 87 devices found in the homekit app
3. Remove device from fibaro (delete device with "id": 56, ": "Bagno Piccolo Temp"), recompile and reinstall as 2.2.4, restart homebridge
outcome: 86 devices found in the homekit app
4. Re-add device to fibaro (revert deletion of device with "id": 56, ": "Bagno Piccolo Temp"), recompile and reinstall as 2.2.4, restart homebridge
outcome: 87 devices found in the homekit app

So far no device was doubled under different manufacturer after update to 2.2.4
Device was correctly deleted from homekit app after deletion from fibaro.

Only thing I found suspicious were errors in the json you posted:
				"remoteGatewayId": 2,
				"viewXml": false,
				"configXml": false,
				"remoteGatewayId": 2,
remoteGatewayId is sometimes doubled.

Can you please check if the device disappears from the json if you remove it from the account? And maybe post json before and after deletion.

Br,
Petr

**Comment by redeemer666** [comment]
Will check and let you know Petr, thank you.

Netatmo is a weather station, configured in HC2 with a plugin (now deleted on it).

Thank you for your help, will keep you posted

**Comment by redeemer666** [comment]
Just a question: I have npm 5.6.0, is safe to update it to 6.9.0? Can it help sorting this thing out?

**Comment by redeemer666** [comment]
Another quick update:
- I have tried to delete the "accessories" and "persist" folder. No luck, the dead accessories still appears in home app.
- I have reverted to version 2.2.3 (without touching anything else) and all the accessories deleted from the HC2 user have disappeared correctly from the Home app...

Is it possible that the issue appear when you don't login as superuser? I have a standard user only for homebridge,, that I use because don't want to see all my Fibaro accessories in the Home App.

**Comment by hovorkap** [comment]
Not sure. Do you use variable switches? They are buggy in 2.2.4. Do you observe any errors in the log in 2.2.4?

**Comment by redeemer666** [comment]
Nope, no variable switches on my setup. How Do I check for error logs? I have tried to start homebridge in Debug mode, but didn't observe anything out of the ordinary.

**Comment by ilcato** [comment]
@redeemer666, send me via email an address to call you; I want to understand your whole setup, because I’m not able to reproduce the problem too.

**Comment by ilcato** [comment]
Solved in latest version.
