### ISSUE TITLE
Sensative Strips Guard BUG

### ISSUE THREAD

**Issue by CHTHSCH** [ilcato/homebridge-Fibaro-HC2#153]
@ilcato I like the homebridge-Fibaro plugin

Yesterday I have added three Sensative Strips Guard door/window sensors. These are represented in HC as motion sensor and as door/window sensor. Only the motion sensor gets transferred through this plugin, not the door/window sensor.

Would appreciate, if this gets corrected

**Comment by CHTHSCH** [comment]
Any comment?

**Comment by ilcato** [comment]
Do not have such a device on order to test it

**Comment by CHTHSCH** [comment]
I can provide information and test if necessary. 

Here is the link to the device/supplier
https://sensative.com/strips/guard/

Will send information about how the device is represented in Home Center tonight

**Comment by CHTHSCH** [comment]
<img width="779" alt="sens1" src="https://user-images.githubusercontent.com/50621196/58929357-f3e02100-8756-11e9-8ecc-a3dcbfdd6f71.png">

<img width="767" alt="sens2" src="https://user-images.githubusercontent.com/50621196/58929372-0195a680-8757-11e9-9676-d331c880080a.png">

<img width="769" alt="sens3" src="https://user-images.githubusercontent.com/50621196/58929379-08241e00-8757-11e9-81fa-b54e5a183163.png">

<img width="765" alt="sens4" src="https://user-images.githubusercontent.com/50621196/58929386-0d816880-8757-11e9-8ee4-caf3ab470cc3.png">

**Comment by CHTHSCH** [comment]
And this is the xml you can download in HCL

[id-019A-0003-0003-00-08-Sensative-.xml.zip](https://github.com/ilcato/homebridge-Fibaro-HC2/files/3268455/id-019A-0003-0003-00-08-Sensative-.xml.zip)

**Comment by ilcato** [comment]
@CHTHSCH, can you send me the json of the response to the rest api call ?

**Comment by CHTHSCH** [comment]
I have meanwhile retired my HC2 and I am using a Raspberry with openHAB. However, you might find the JSON string in the Z-Wave Device database (see here: https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/251)

And the JSON I downloaded from that site

{
    "database_id": 251,
    "label": "11-01-011",
    "manufacturer_name": "Sensative AB",
    "manufacturer_id": "019A",
    "device_ref": [
        "0003:0003"
    ],
    "version_min": 0,
    "version_max": 255.255,
    "decription": "Strips-MaZw",
    "overview": "",
    "inclusion": "<ul><li>Set your controller in inclusion mode (see your controller\u2019s manual).<\/li> <li>Follow the instruction for Wake up.<\/li> <li>A long LED blink indicates that the inclusion was successful.<\/li> <\/ul>",
    "exclusion": "<ul><li>Set your controller in exclusion mode (see your controller\u2019s manual).<\/li> <li>Follow the instruction for Wake up.<\/li> <li>A long LED blink indicates that the exclusion was successful.<\/li> <\/ul>",
    "wakeup": "<p>Wake up Strips manually for Z-Wave communication.<\/p> <ul><li>Place the round magnet at the rounded edge.<\/li> <li>When the LED blinks, move the magnet away.<\/li> <li>Repeat 3 times in total within 10 seconds.<\/li> <\/ul><p>It may be necessary to repeat this process several times to make changes take affect.<\/p> <p>Note that wakeup period can only be set to a minimum period of 30 minutes.<\/p>",
    "protocol_version": 4.005,
    "listening": false,
    "frequently_listening": false,
    "routing": true,
    "beaming": true,
    "library_type": {
        "id": 7,
        "name": "LIB_CONTROLLER_BRIDGE"
    },
    "basic_class": {
        "id": 4,
        "name": "BASIC_TYPE_ROUTING_SLAVE"
    },
    "generic_class": {
        "id": 4,
        "name": "GENERIC_TYPE_SENSOR_NOTIFICATION"
    },
    "specific_class": {
        "id": 4,
        "name": "SPECIFIC_TYPE_NOTIFICATION_SENSOR"
    },
    "endpoints": [
        {
            "id": 0,
            "basic_class": {
                "id": 4,
                "name": "BASIC_TYPE_ROUTING_SLAVE"
            },
            "generic_class": {
                "id": 7,
                "name": "GENERIC_TYPE_SENSOR_NOTIFICATION"
            },
            "specific_class": {
                "id": 1,
                "name": "SPECIFIC_TYPE_NOTIFICATION_SENSOR"
            },
            "commandclasses": [
                {
                    "id": "00",
                    "name": "NO_OPERATION",
                    "version": "1",
                    "nif": false,
                    "basic": false,
                    "secure": false,
                    "nonsecure": true,
                    "config": "",
                    "channels": []
                },
                {
                    "id": "20",
                    "name": "BASIC",
                    "version": "1",
                    "nif": false,
                    "basic": false,
                    "secure": false,
                    "nonsecure": true,
                    "config": "",
                    "channels": []
                },
                {
                    "id": "30",
                    "name": "SENSOR_BINARY",
                    "version": "1",
                    "nif": false,
                    "basic": false,
                    "secure": false,
                    "nonsecure": true,
                    "config": "NOGET",
                    "channels": []
                },
                {
                    "id": "70",
                    "name": "CONFIGURATION",
                    "version": "1",
                    "nif": false,
                    "basic": false,
                    "secure": false,
                    "nonsecure": true,
                    "config": "",
                    "channels": []
                },
                {
                    "id": "71",
                    "name": "ALARM",
                    "version": "3",
                    "nif": false,
                    "basic": false,
                    "secure": false,
                    "nonsecure": true,
                    "config": "",
                    "channels": [
                        {
                            "type": "sensor_door",
                            "label": "Door Sensor",
                            "config": [
                                "type=ACCESS_CONTROL"
                            ]
                        },
                        {
                            "type": "alarm_tamper",
                            "label": "Tamper Alarm",
                            "config": [
                                "type=BURGLAR"
                            ]
                        }
                    ]
                },
                {
                    "id": "72",
                    "name": "MANUFACTURER_SPECIFIC",
                    "version": "1",
                    "nif": false,
                    "basic": false,
                    "secure": false,
                    "nonsecure": true,
                    "config": "",
                    "channels": []
                },
                {
                    "id": "80",
                    "name": "BATTERY",
                    "version": "1",
                    "nif": false,
                    "basic": false,
                    "secure": false,
                    "nonsecure": true,
                    "config": "",
                    "channels": []
                },
                {
                    "id": "84",
                    "name": "WAKE_UP",
                    "version": "2",
                    "nif": false,
                    "basic": false,
                    "secure": false,
                    "nonsecure": true,
                    "config": "",
                    "channels": []
                },
                {
                    "id": "85",
                    "name": "ASSOCIATION",
                    "version": "1",
                    "nif": false,
                    "basic": false,
                    "secure": false,
                    "nonsecure": true,
                    "config": "",
                    "channels": []
                },
                {
                    "id": "86",
                    "name": "VERSION",
                    "version": "1",
                    "nif": false,
                    "basic": false,
                    "secure": false,
                    "nonsecure": true,
                    "config": "",
                    "channels": []
                }
            ]
        }
    ],
    "parameters": [
        {
            "id": 1,
            "label": "Notification type",
            "description": "Define the notification type.",
            "overview": "",
            "size": 1,
            "bitmask": "00000000",
            "default": 1,
            "read_only": false,
            "write_only": false,
            "value_min": 0,
            "value_max": 255,
            "options": [
                {
                    "value": 0,
                    "label": "Binary Sensor report"
                },
                {
                    "value": 1,
                    "label": "Notification report"
                },
                {
                    "value": 2,
                    "label": "Basic report"
                }
            ]
        },
        {
            "id": 2,
            "label": "LED indication",
            "description": "Specify if LED should indicate special event.",
            "overview": "",
            "size": 1,
            "bitmask": "00000000",
            "default": 1,
            "read_only": false,
            "write_only": false,
            "value_min": 0,
            "value_max": 255,
            "options": [
                {
                    "value": 0,
                    "label": "Off"
                },
                {
                    "value": 1,
                    "label": "On"
                }
            ]
        }
    ],
    "associations": [
        {
            "id": 1,
            "label": "Lifeline",
            "max_nodes": 1,
            "controller": true,
            "description": "",
            "overview": ""
        }
    ]
}

**Comment by ilcato** [comment]
I need the json coming from home center.
