### ISSUE TITLE
SecuritySystem and Roller Shutters doesn't report final state on Home App.

### ISSUE THREAD

**Issue by redeemer666** [ilcato/homebridge-Fibaro-HC2#156]
Hello guys,

found another bug in 2.2.4, that was working correctly on 2.2.3. Roller shutters and security system remains stuck on "activating status" (like "closing", "opening", "arming", "disarming") even after the activity has been completed. To correctly update the status, you have to force close the "Home" app and reopen it. If you do this workaround, all statuses will update correctly.

**Comment by ilcato** [comment]
Solved in the current release.
