### ISSUE TITLE
Sensor Triggers on V2.2.4

### ISSUE THREAD

**Issue by juanolivier** [ilcato/homebridge-Fibaro-HC2#158]
Automations built on movement sensor triggers stop working on version 2.2.4. 
Tests:
1)If the home app is open and the movement is triggered it will sometimes work
2)If movement sensor is triggered and the home app opens with the sensor still reflecting triggered the automation worked everytime.
3)Home app closed the automation does not work when a movement sensor is tripped.

Rolled back to version 2.2.2, the version i upgraded from, worked immediately without having to even open the home app on my iphone.

Thanks for all the brilliant work!
=)

**Comment by ilcato** [comment]
@juanolivier, can you test with the current version?

**Comment by ilcato** [comment]
Closing it. Reopen if you have updates
