### ISSUE TITLE
Fibaro Walli support?

### ISSUE THREAD

**Issue by danholt-international** [ilcato/homebridge-Fibaro-HC2#160]
Hi! The new Fibaro Walli outlets, switches and dimmer do not pop up in HomeKit when added to a Fibaro HCL or HC2 gateway.

**Comment by Pascal26120** [comment]
Hi

I have the same issue with myself HC2 gateway. They are not listed on homebridge log on startup

**Comment by Pascal26120** [comment]
Up

**Comment by Pascal26120** [comment]
It's urgent

**Comment by ilcato** [comment]
Sorry guys but without devices available I cannot implement and test it.

**Comment by danholt-international** [comment]
Well, should we sponsor these?
Fibaro Walli already available: 
https://www.danholt.de/cms/frontend/suche_shop.php?Suchbegriff=walli&submitButtonName.x=0&submitButtonName.y=0&dieseinfobox=30&naviID=0&ueber=0&sprache=deutsch

**Comment by danholt-international** [comment]
Hello again! Is there any chance to implement support for Fibaro Walli devices soon? What can we do to assist you?

**Comment by ilcato** [comment]
Can you send me the result of the inquiry of the devices through the rest api?

**Comment by danholt-international** [comment]
Hi!

Hre is an example of the Walli Dimmer... please let me know, if this date is what you need and we will prepare this data for Walli outlet, switch and roller shutters too.
[Walli dimmer.txt](https://github.com/ilcato/homebridge-Fibaro-HC2/files/3486109/Walli.dimmer.txt)

**Comment by ilcato** [comment]
@danholt-international can you test it ?

**Comment by danholt-international** [comment]
😊 👍 it works for the dimmer!
So I guess you need the results of the rest api for outlet, switch and roller shutter now...
[Walli dimmer.txt](https://github.com/ilcato/homebridge-Fibaro-HC2/files/3487378/Walli.dimmer.txt)
[Walli outlet -type F.txt](https://github.com/ilcato/homebridge-Fibaro-HC2/files/3487381/Walli.outlet.-type.F.txt)
[Walli switch.txt](https://github.com/ilcato/homebridge-Fibaro-HC2/files/3487385/Walli.switch.txt)

**Comment by danholt-international** [comment]
Missed the Roller Shutter... sorry!

[Walli RollerShutter.txt](https://github.com/ilcato/homebridge-Fibaro-HC2/files/3487555/Walli.RollerShutter.txt)

**Comment by ilcato** [comment]
@danholt-international can you test it ?

**Comment by danholt-international** [comment]
Works! 👍 
Great job! Even the venetian blend mode works fine in testing mode.
I will install a shutter now to a real blend and test even further, but I am sure it will work too as done in testing mode.

Also the switch works fine... one-load and two loads can be controlled perfectly.

Very happy with this !  🥇  😊

**Comment by ilcato** [comment]
@danholt-international, feel free to involve me in the discussion you mention.

**Comment by danholt-international** [comment]
Hi! Just tested the RollerShutter in real life and it works fine including lamella positioning!
I will let you know, when I have talked with guys from Fibaro.

**Comment by Pascal26120** [comment]
Hi,
Works perfectly with walli outlet.
on the other hand with walli dimmer, when I turn on the light by homekit, it goes immediately. I specify that by  fibaro app it works perfectly
Regards

**Comment by ilcato** [comment]
@pascal26120, not sure to understand the issue.

**Comment by Pascal26120** [comment]
@ilcato Sory 
issue is solved

**Comment by danholt-international** [comment]
Hello!

Is it correct that the current version of the hc2 plugin crashes homebridge 1.0.2 installations?

Tied several time and had to reinstall homebridge from scratch.
Instantly after installing the hc2 plugIn a restart of homebridge fails.

Regards

Daniel

**Comment by ilcato** [comment]
Working on it.

**Comment by danholt-international** [comment]
Great! Any prediction when update available?
Our house is offline currently :(

Best

Daniel

**Comment by ilcato** [comment]
@danholt-international, just fixed. Please upgrade the plugin to the latest version.

**Comment by danholt-international** [comment]
Roller shutter and Walli Roller Shutter: Lamellas adjustment has gone.

Regards
Daniel

Von meinem iPhone gesendet

**Comment by danholt-international** [comment]
Hello!

Even version 2.3.4 for Fibaro HC2 fixes the issue:
There is no slider available in Home App to adjust the lamellas of Venetian blinds.
In earlier Versions and before Homebridge 1.x these sliders have been available.

They have gone now…
Is it possible to fix this please?

Regards

Daniel

**Comment by ilcato** [comment]
@danholt-international, please try version 2.3.5.
Open a new issue in case of problem. This issue is closed and relates to another problem.
Thanks

**Comment by danholt-international** [comment]
I’m sorry, v. 2.3.5 does not solve the issue.

Regards

Daniel
