### ISSUE TITLE
"Cannot read property 'pollerperiod' of null" when plugin is not in use

### ISSUE THREAD

**Issue by Krillle** [ilcato/homebridge-Fibaro-HC2#165]
When starting Homebridge where Fibaro-HC2 plugin is installed but not in use (e.g. in a second instance on the same device, to not exceed the number of devices) Homebridge crashes with the exception "Cannot read property 'pollerperiod' of null":

```
Aug 10 01:37:12 Homebridge homebridge[21793]: Load homebridge-fibaro-hc2.FibaroHC2
Aug 10 01:37:12 Homebridge homebridge[21793]: /usr/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:67
Aug 10 01:37:12 Homebridge homebridge[21793]:         let pollerPeriod = this.config.pollerperiod ? parseInt(this.config.pollerperiod) : defaultPollerPeriod;
Aug 10 01:37:12 Homebridge homebridge[21793]:                                        ^
Aug 10 01:37:12 Homebridge homebridge[21793]: TypeError: Cannot read property 'pollerperiod' of null
Aug 10 01:37:12 Homebridge homebridge[21793]:     at new FibaroHC2 (/usr/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:67:40)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:346:30)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:87:8)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at Module._compile (module.js:652:30)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at Object.Module._extensions..js (module.js:663:10)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at Module.load (module.js:565:32)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at tryModuleLoad (module.js:505:12)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at Function.Module._load (module.js:497:3)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at Function.Module.runMain (module.js:693:10)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at startup (bootstrap_node.js:191:16)
Aug 10 01:37:12 Homebridge homebridge[21793]:     at bootstrap_node.js:612:3
Aug 10 01:37:12 Homebridge systemd[1]: homebridge-tesla.service: Main process exited, code=exited, status=1/FAILURE
Aug 
```

Plugin should abort when no parameters are found.

**Comment by ilcato** [comment]
@Krillle, this is normally a case in whiuch homebridge is not able to read the config.json file.
Please be sure to have the file in the .homebridge directory of the user that launch the homebridge program or to specify the config.json location in the command line.

**Comment by Krillle** [comment]
Yes, I know. And also in case there is no section for Fibaro defined. Means the plugin is installed, but no in uses. This happens for example if you have two instances of homebriudge running on same raspberry pi.

Problem is here:
```let pollerPeriod = this.config.pollerperiod ? parseInt(this.config.pollerperiod) : defaultPollerPeriod;```
This crashes if no pollerPeriod is found in config file.
https://github.com/ilcato/homebridge-Fibaro-HC2/blob/dd926384229b97a3518e421ec4407683e084d7ba/src/index.ts#L117

**Comment by ilcato** [comment]
No @Krillle the error says that `this.config` is null, so homebridge was not able to instantiate a config object for the plugin. I will check this case and exit the constructor without crashing.
Give me 15 minutes and try with the new version.

**Comment by Krillle** [comment]
I send a pull request with my proposal.

**Comment by Krillle** [comment]
`this.config` is null in a valid context, in case home bridge is started with the fibaro-hc2 plugin installed, while it is not in use. Means no section for fibaro plugin in config.json.

This is a valid scenario. The plugin should not crash homebridge then.

**Comment by ilcato** [comment]
please do

**Comment by Krillle** [comment]
You changed already. I would have done same way.

**Comment by ilcato** [comment]
Yes, but this create a TS compilation problem. Will fix it.

**Comment by ilcato** [comment]
@Krillle, can you try?

**Comment by ilcato** [comment]
@Krillle, were you able to test it?

**Comment by Krillle** [comment]
Thanks for coming back to it. Unfortuately i didn't find the time yet.

**Comment by ilcato** [comment]
@Krillle, any news?

**Comment by ilcato** [comment]
@Krillle, any chance to have this tested by you? It works for me. I will close the issue the next week.

**Comment by Krillle** [comment]
Yes it works for me now. Thank you for fixing. 
Btw I learned that the new parameter -x is doing the same thing.

**Comment by ilcato** [comment]
ok
