### ISSUE TITLE
Motion sensor - no more than 10.000lux

### ISSUE THREAD

**Issue by danholt-international** [ilcato/homebridge-Fibaro-HC2#167]
A fibaro motion sensor that reports more than 10.000 Lux in the Fibaro Home Center App stucks in HomeKit at 10.000lux.
So in HomeKit the displayed value is 10.000lx permanently as long as the sensor senses values abobe 
<img width="824" alt="Bildschirmfoto 2019-08-14 um 11 14 18" src="https://user-images.githubusercontent.com/52234886/63016298-958c9880-be93-11e9-9e0a-6f436dda72ec.png">
<img width="874" alt="Bildschirmfoto 2019-08-14 um 12 58 59" src="https://user-images.githubusercontent.com/52234886/63016307-9a514c80-be93-11e9-869f-6b2b3784ca2a.png">

I am not sure if this is an issue of HomeKit Home App or an issue of the homebridge PlugIn.

**Comment by ilcato** [comment]
I don't remember why I limited it. If you can test it I set the max value to 100000 that is direct sunlight. Install it from github and not from npm, it is not yet published on npm.

**Comment by danholt-international** [comment]
Hi!

No chance today to test… I am on a business trip.
Please if possible load the update onto npm and I can arrange that one of our employees can update our homebridge and test it.

Regards

Daniel

**Comment by ilcato** [comment]
You can install it with:
`npm install -g https://github.com/ilcato/homebridge-Fibaro-HC2.git`

**Comment by danholt-international** [comment]
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/ilcato/homebridge-Fibaro-HC2.git /root/.npm/_cacache/tmp/git-clone-ba590fc7/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-ba590fc7/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-15T11_19_34_457Z-debug.log

**Comment by ilcato** [comment]
are you executing the command with root rights?

**Comment by danholt-international** [comment]
yes

**Comment by ilcato** [comment]
run the `sudo -s` command and then `npm install -g https://github.com/ilcato/homebridge-Fibaro-HC2.git`

**Comment by danholt-international** [comment]
same issue, sorry
Will wait for the next official update.

Regards

Daniel

**Comment by danholt-international** [comment]
Hi!

Any idea when you will publish the next official update release?

**Comment by ilcato** [comment]
Tonight

**Comment by ilcato** [comment]
published

**Comment by danholt-international** [comment]
Still 10.000 Lux max in Home App 🙁

**Comment by ilcato** [comment]
Did you restart homebridge? I’m out of home till next week, cannot test directly.

**Comment by danholt-international** [comment]
yes, i restarted homebridge.
Maybe this is of interes too:
The only sensor available in Home App to create an automation is motion.
The LUX are not available and no temperature too.

**Comment by ilcato** [comment]
@danholt-international, I fear that the old limit (10000) is stored on the homebridge local database. Are you able to test it on a fresh installation or to remove the accessories folder ?
Regarding the opportunity to use a lux sensor as a trigger I think its a limit of the Home app. Other apps are able to use it.

**Comment by danholt-international** [comment]
Deleting the accessories folder made my day 😉 LUX values are correct now and also above the 10.000lux limit. GREAT! Had to rearrange all my devices in HomeKit because of the deletion of the accessories folder ... maybe there is some other solution to readjust the accessories in HomeBridge as any user who already has a motion sensor already in use, will run into the same problem when updating.
