### ISSUE TITLE
Positioning is enabled even for shutter with positioning inactive

### ISSUE THREAD

**Issue by lboue** [ilcato/homebridge-Fibaro-HC2#172]
Hello,

I am facing an issue with my blind (FGRM222) with positioning inactive on HC2 side. Positioning reported as enabled on HomeKit app and I can see it on the log file :
```
0|homebrid | [2019-11-8 9:51:38 PM] [FibaroHC2] Getting value from device:  203  parameter: Target Horizontal Tilt Angle
0|homebrid | [2019-11-8 9:51:38 PM] [FibaroHC2] Getting value from device:  203  parameter: Target Position
0|homebrid | [2019-11-8 9:51:38 PM] [FibaroHC2] Getting value from device:  203  parameter: Current Position
```

This was introcuced with commit b22f5b19becb1421decc2a0efdba8de0f1844abb.

You should check the 'deviceControlType' properties:
```
   "properties":{
      "parameters":[],
      "pollingTimeSec":0,
      "zwaveCompany":"Fibargroup",
      "zwaveInfo":"3,3,52",
      "zwaveVersion":"22.22",
      "RFProtectionState":"0",
      "RFProtectionSupport":"0",
      "categories":"[\"blinds\"]",
      "configured":true,
      "dead":"false",
      "deadReason":"",
      "deviceControlType":"53",
      "deviceGroup":"[]"
   }
```
Table for shutter module:

- value="53" --> Blind with positioning inactive
- value="54" --> Blind with positioning active
- value="55" --> Venetian blind
- value="56" --> Garage Door without positioning
- value="57" --> Garage Door with positioning

I would propose something like this commit to fix it:
9d0ca3fe0d85814900b2721d7d00c88c26b282d4

Regards
Ludovic

**Comment by ilcato** [comment]
merged

**Comment by lboue** [comment]
Thanks
