### ISSUE TITLE
Fibaro on Hoobs System

### ISSUE THREAD

**Issue by mastersteven** [ilcato/homebridge-Fibaro-HC2#177]
i habe Home Center 2 with many devices. When I want to config the Fibrao Plugin on my Hoobs System (www.hoobs.org) and save this, my hoobs does not run. So I must deinstall the fibaro plugin. Can you help me, to run this on my hoobs?

**Comment by ilcato** [comment]
I'm using hoobs with this plugin and it works.
are you able to see the log?
