### ISSUE TITLE
Support Fibaro Dimmer 2

### ISSUE THREAD

**Issue by dgburton** [ilcato/homebridge-Fibaro-HC2#18]
Hi,

To support the Dimmer 2 I think the following needs modifying:
if (s.type == "com.fibaro.multilevelSwitch")
...becomes:

if (s.type == "com.fibaro.multilevelSwitch" || s.type == "com.fibaro.FGD212")

**Comment by ilcato** [comment]
All my Dimmer 2 return as type attribute com.fibaro.multilevelSwitch.

**Comment by ilcato** [comment]
With latest device the com.fibaro.FGD212 is the default type. I'm including your definition.
Thanks.

**Comment by joystick666** [comment]
sorry to say, but the update did not change anything for me, already deleted accessories folder and ios db...and rebooted. Still the Dimmer2 is not visible

**Comment by ilcato** [comment]
Are you sure to have the latest version of the plugin? Sometimes it doesn't upgrade.

**Comment by joystick666** [comment]
ok, I kind of sorted it: I had to delete accessories folder and presist folder, aswell as Homekit DB... now it's showing correctly, Thank you!!!

**Comment by RCJN** [comment]
Hi @joystick666 my Fibaro dimmer 2 does not show in my homebridge as an accessoiry either. Would you please help me? Do you use it via domoticz? Did you use the plugin HC2? and did you change anything in the script?

**Comment by FibaroMexico** [comment]
Hi
I use the homebridge with the HC2 and in the home app the dimmer appears as an ON/OFF switch, anyone have the same issue? how do I make it a multilevel switch?

**Comment by JGalaviz** [comment]
Hi
I use the homebridge with the HC2 and in the home app the dimmer appears as an ON/OFF switch, anyone have the same issue? how do I make it a multilevel switch?

**Comment by ilcato** [comment]
Can you show me the details page of the accessory in the home app?

**Comment by JGalaviz** [comment]
![1](https://user-images.githubusercontent.com/33940556/33219194-a4eb052c-d106-11e7-93bd-5c7f2d8a352f.jpeg)
![2](https://user-images.githubusercontent.com/33940556/33219196-a61c8344-d106-11e7-86d2-8e861a1ddaa0.jpeg)
![3](https://user-images.githubusercontent.com/33940556/33219197-a7790906-d106-11e7-8455-f75eeb6c8408.jpeg)

Here are the screenshots

**Comment by JGalaviz** [comment]
I was on IOS 10.3.3 and in that version everything works fine but the Fibaro Dimmer 2 works as an ON/OFF Switch instead of a dimmer.
I solved this with an update to IOS 11

**Comment by SNOWGUM** [comment]
Unfortunately, I'm getting this issue still? Only recently have I started to get it and I'm not sure why? The Dimmers are showing as **com.fibaro.FGD212**, I'm using the HC3 but up until now I haven't had any problems and nore should I as the API hasn't changed. Just wondering if anyone knows what's going on.

**Comment by ilcato** [comment]
> Unfortunately, I'm getting this issue still? Only recently have I started to get it and I'm not sure why? The Dimmers are showing as **com.fibaro.FGD212**, I'm using the HC3 but up until now I haven't had any problems and nore should I as the API hasn't changed. Just wondering if anyone knows what's going on.

@SNOWGUM, for HC3 a specific plugin exists: homebridge-fibaro-hc3
