### ISSUE TITLE
New RGBW 2 controller not added

### ISSUE THREAD

**Issue by TimE90** [ilcato/homebridge-Fibaro-HC2#184]
Hey!

My new RGBW 2 controller is not added to HomeKit. I've update to 2.3.1 and the Fibaro devices API also shows the device. But when starting homebridge it's not added/found. What am I doing wrong?

{
"id":496,
"name":"LED Decke",
"roomID":2,
"type":"com.fibaro.FGRGBW442CC",
"baseType":"com.fibaro.colorController",
"enabled":true,
"visible":true,
"isPlugin":false,
"parentId":493,
"remoteGatewayId":0,
"viewXml":false,
"configXml":false,
"interfaces":[
"deviceGrouping",
"energy",
"levelChange",
"light",
"power",
"zwave",
"zwaveAlarm",
"zwaveMultiChannelAssociation",
"zwaveProtection"
]…

**Comment by TineTurk** [comment]
In my case it was automatically added once Ilcato updated shadows.

**Comment by TimE90** [comment]
Now it works. I‘ve updated the wrong npm directory :) sorry for this!

**Comment by TineTurk** [comment]
:)

Btw, I noticed some issues with setting up the color. LEt me know your experiences.

**Comment by TimE90** [comment]
I didn't notice any color issues. Can you explain the steps to reproduce your issues?

**Comment by TineTurk** [comment]
I noticed one more thing, but I'm not sure if this "issue" is insulated to FGRGBW-442 or is a general thing.

If I set specific color on iPhone at a low brightness, RGBW parameters on HC2 will be set proportionally low. If I set the same color on iPhone when brightness is set higher, RGBW parameters will be positioned proportionally higher. In both cases if I adjust brightness RGBW parameters remain at the same level, therefore producing different color even if matching brightness.

Example of setting one color under low brightness:
![image](https://user-images.githubusercontent.com/50627739/79269462-c72f8680-7e9c-11ea-9a3f-8ff0811c4ac6.png)
![image](https://user-images.githubusercontent.com/50627739/79269501-dadaed00-7e9c-11ea-89ff-877e6c958826.png)

Then increasing only brightness on iPhone:
![image](https://user-images.githubusercontent.com/50627739/79269537-e8907280-7e9c-11ea-9f9c-c7df42a87bf9.png)
![image](https://user-images.githubusercontent.com/50627739/79269545-ed552680-7e9c-11ea-83b4-df32c54d583f.png)

If the same color is set while having set higher brightness we get the following situation:
![image](https://user-images.githubusercontent.com/50627739/79269575-fcd46f80-7e9c-11ea-9870-79a3ad2a75e3.png)
![image](https://user-images.githubusercontent.com/50627739/79269594-0362e700-7e9d-11ea-82ee-b1a32065aabf.png)

And then if I decrease brightness to 1% on the iPhone:
![image](https://user-images.githubusercontent.com/50627739/79269621-0eb61280-7e9d-11ea-9a91-54b92c9f1af3.png)
![image](https://user-images.githubusercontent.com/50627739/79269639-12e23000-7e9d-11ea-9b56-36c876fca32b.png)

The end result is, that you can get different light under the same color setting & brightness value, depending on the brightness value at the momemnt when setting the color.
