### ISSUE TITLE
Missing devices in the object list

### ISSUE THREAD

**Issue by fjosepose** [ilcato/homebridge-Fibaro-HC2#199]
Hi
I´m using the Homebridge/Fibaro Plug-in in ioBroker. My problem is that not all my devices from the HC2 are "imported" into ioBridge, and some devices are missing in the object list. I have tried clean installs/restarts etc, but no improvement. My current connection HC2<->ioBridge have the following metrics, Objects=3563 and States=2986.

I do not know if this is a matter of me doing something wrong or if theres is a bug in the plug-in/adapter?

**Comment by fjosepose** [comment]
One example of missing device is the ventilation system here in HC2:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/17417348/93066915-d6e50e00-f67a-11ea-9652-c24ea5fafbdd.png">

while in ioBrokers object list the ventilation system appears as:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/17417348/93067032-fe3bdb00-f67a-11ea-9787-a79bebe06b65.png">

This makes the fan speed not possible to adjust from ioBroker

**Comment by fjosepose** [comment]
The fan of my AC-system is also missing, so it seems that there is some kind of general fan-issue where "type": "com.fibaro.fanMode" ?

**Comment by baafonso** [comment]
see comment on #126 .

**Comment by ilcato** [comment]
@fjosepose, it should be fixed in 2.3.7

**Comment by hughc-hub** [comment]
Hi,

After last update, I'm having unresponsive results. 
From HomeKit I have "missing message" from all devices, but If I enter into the web page of homebridge where you can see all devices, then in HomeKit appears for a while. It´s like once you enter there it activates something that makes everything works.
Any idea?

thanks a lot

**Comment by ilcato** [comment]
try 2.4.3
