### ISSUE TITLE
“Nice” garage door opener not recognized by plugin

### ISSUE THREAD

**Issue by redeemer666** [ilcato/homebridge-Fibaro-HC2#200]
Hi there!

I have just added to my Fibaro system a “Nice” Interface for garage doors (https://www.niceforyou.com/en/nicepost/nice-now-open-z-wavetm-smart-home-world, https://smarterhome.sk/en/garage-doors-and-gates/fibaro-nice-bidi-zwave-ibt4zwave-858.html). Fibaro recognize it without hassle, but it doesn’t appear on HomeKit.

Can you help me?

Grazie

**Comment by redeemer666** [comment]
Works like a roller shutter, so standard close, open, stop midway. No extra configurations, at least on my garage door

**Comment by baafonso** [comment]
can you please provide the output of:

http://_YOUR_FIBARO_IP_ADDRESS/api/devices/ID_OF_NICE_GARAGE_INTERFACE and whatever other IDs are related to it?

**Comment by redeemer666** [comment]
Hi Baafonso,

is this right?
[GET command.pdf](https://github.com/ilcato/homebridge-Fibaro-HC2/files/5354679/GET.command.pdf)

**Comment by redeemer666** [comment]
Or this one?

{"id":30,"name":"Porta Garage","roomID":1,"type":"com.fibaro.baseShutter","baseType":"com.fibaro.actor","enabled":true,"visible":true,"isPlugin":false,"parentId":29,"remoteGatewayId":0,"interfaces":["fibaroFirmwareUpdate","stepByStep","zwave","zwaveAlarm","zwaveMultiChannelAssociation","zwaveProtection"],"properties":{"parameters":[{"id":30,"lastReportedValue":0,"lastSetValue":0,"size":4,"value":0},{"id":31,"lastReportedValue":100597760,"lastSetValue":100597760,"size":4,"value":100597760},{"id":32,"lastReportedValue":33488896,"lastSetValue":33488896,"size":4,"value":33488896},{"id":33,"lastReportedValue":50266112,"lastSetValue":50266112,"size":4,"value":50266112},{"id":34,"lastReportedValue":83820544,"lastSetValue":83820544,"size":4,"value":83820544}],"pollingTimeSec":0,"zwaveCompany":"","zwaveInfo":"3,7,13","zwaveVersion":"7.0","RFProtectionState":"0","RFProtectionSupport":"3","alarmLevel":"0","alarmType":"0","categories":"[\"gates\"]","configured":true,"dead":"false","deadReason":"","deviceControlType":"60","deviceIcon":"196","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","firmwareUpdate":"{\"info\":\"\",\"progress\":0,\"status\":\"UpToDate\",\"updateVersion\":\"7.0\"}","localProtectionState":"0","localProtectionSupport":"5","log":"","logTemp":"","manufacturer":"","markAsDead":"true","model":"","nodeId":"6","parametersTemplate":"875","productInfo":"4,65,36,0,16,0,7,0","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"h'000000000000071d","smsNotificationID":"0","smsNotificationType":"0","state":"Closed","updateVersion":"","useTemplate":"true","userDescription":""},"actions":{"abortUpdate":1,"close":0,"open":0,"reconfigure":0,"retryUpdate":1,"startUpdate":1,"step":0,"stop":0,"updateFirmware":1},"created":1600792805,"modified":1600792805,"sortOrder":29}

**Comment by baafonso** [comment]
can you send the output with ID 29?

**Comment by redeemer666** [comment]
Here you go

{"id":29,"name":"29","roomID":0,"type":"com.fibaro.zwaveDevice","baseType":"com.fibaro.device","enabled":true,"visible":false,"isPlugin":false,"parentId":1,"remoteGatewayId":0,"interfaces":["polling","zwave","zwaveAssociation","zwaveConfiguration","zwaveMultiChannelAssociation","zwaveProtection","zwaveSlaveRouting"],"properties":{"RFProtectionState":"0","RFProtectionSupport":"3","associations":"[{\"endPointId\":0,\"groups\":[{\"groupInfo\":{\"commands\":[{\"command\":\"Device Reset Locally Notification\",\"commandClass\":\"Command Class Device Reset Locally\"},{\"command\":\"Switch Multilevel Report\",\"commandClass\":\"Command Class Switch Multilevel\"},{\"command\":\"Notification Report\",\"commandClass\":\"Command Class Notification\"}],\"name\":\"Lifeline\",\"profile\":\"General: Lifeline\"},\"id\":1,\"multiChannel\":{\"bitAddressable\":false,\"max\":1,\"set\":[{\"endPointId\":[0],\"nodeId\":1}],\"view\":[{\"endPointId\":[0],\"nodeId\":1}]},\"singleChannel\":{\"max\":1,\"set\":[],\"view\":[]}}]}]","categories":"[\"other\"]","configured":true,"dead":"false","deadReason":"","deviceControlType":"0","deviceIcon":"28","deviceSpecificData":"h'000000000000071d","deviceSpecificIdType":"Serial Number","deviceState":"Configured","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","lastWorkingRoute":"[1,5]","lastWorkingRouteRequestStatus":"ok","lastWorkingRouteRequestTimestamp":"0","lastWorkingRouteResponseTimestamp":"1600792836","localProtectionState":"0","localProtectionSupport":"5","log":"","logTemp":"","manufacturer":"","markAsDead":"true","model":"","neighborList":"[1,5]","neighborListRequestStatus":"ok","neighborListRequestTimestamp":"0","neighborListResponseTimestamp":"1600792836","nodeId":"6","parameters":[{"id":30,"lastReportedValue":0,"lastSetValue":0,"size":4,"value":0},{"id":31,"lastReportedValue":100597760,"lastSetValue":100597760,"size":4,"value":100597760},{"id":32,"lastReportedValue":33488896,"lastSetValue":33488896,"size":4,"value":33488896},{"id":33,"lastReportedValue":50266112,"lastSetValue":50266112,"size":4,"value":50266112},{"id":34,"lastReportedValue":83820544,"lastSetValue":83820544,"size":4,"value":83820544}],"parametersTemplate":"875","pollingInterval":"0","pollingTimeSec":0,"productInfo":"4,65,36,0,16,0,7,0","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"h'000000000000071d","smsNotificationID":"0","smsNotificationType":"0","useTemplate":"true","userDescription":"","zwaveCompany":"","zwaveInfo":"3,7,13","zwaveSoftwareVersion":"{}","zwaveVersion":"7.0"},"actions":{"getLastWorkingRoute":0,"getNeighborList":0,"getParameter":1,"poll":0,"reconfigure":0,"requestNodeNeighborUpdate":0,"setParameter":2},"created":1600792805,"modified":1600792805,"sortOrder":28}

**Comment by baafonso** [comment]
I don't have a garage door opener, so this is absolutely untested.

If you are confortable editing files on linux:

open a console on homebridge and execute:

cd /usr/local/lib/node_modules/homebridge-fibaro-hc2/dist/
sudo nano shadows.js

find a line with the following (about 170 lines down more or less); 

			case "com.fibaro.barrier":


change to:
			case "com.fibaro.baseShutter":
			case "com.fibaro.barrier":

save
restart homebridge
try
if you fail it might be required to re-install homebridge and a thermonuclear war may occur. try at own risk. (you get the picture)
good luck

**Comment by redeemer666** [comment]
OK so.... Quite comfortable about the thermonuclear war... not the same with reinstalling homebridge... :) will make a a backup and try. Keep you posted.

Thanks in either cases!!

**Comment by redeemer666** [comment]
OK, it's a bit hot today here but google report no wars occurring in this area...

Added the line you told me and the device appeared immediately in Home app. First glance it works (opened and closed without issue), will give a thorough testing this weekend and update this ticket on Sunday.

Thanks Thanks Thanks

**Comment by ilcato** [comment]
@redeemer666, added into 2.3.7

**Comment by redeemer666** [comment]
First test done:
Open-Close command works very good. They also works in the "act" of opening and closing (if you close when it's opening, it will close and vice versa).

Have to try if using the remote will report the correct status into home app. Will update it later.

Notice: The accessory is like a switch, it doesn't have the "opening" and "closing" status. When you click on it, it will change as "open" or "close" even when the door is opening or closing. May be a limitation of the HomeKit integration itself though.

Thanks a lot for the help, to all of you. Will update the plugin so I will not cause any thermonuclear war anymore eheh.

**Comment by redeemer666** [comment]
OK Last update.

Everything works perfectly. Door status recognized correctly even when used with it's own radio or directly via the central controls. 

Controls are very stable and it also recognizes the "error" when an obstacle block the door.

Thanks all of you for this, keep up the really good job you're doing. Best homebridge plugin ever.

Closing this one.
