### ISSUE TITLE
Support for HomeBridge 2.x or 3.x

### ISSUE THREAD

**Issue by neilpatel121** [ilcato/homebridge-Fibaro-HC2#202]
Tried updating to the new version of HomeBridge, unable to turn lights on or off.

**Comment by ilcato** [comment]
With the latest release you should be able to update to HomeBridge 1.3 that is the latest version of HomeBridge.
What do you mean with this issue?

**Comment by neilpatel121** [comment]
Thanks mate, I'll try it out and share stack trace if any issues.
