### ISSUE TITLE
Hanged HCL blocks all other plugins in Homebridge

### ISSUE THREAD

**Issue by sylwesterr** [ilcato/homebridge-Fibaro-HC2#203]
When for any reason HCL is unavailable, the plugin blocks response from all other plugins within Homebridge instance.
According to 
https://github.com/homebridge/homebridge/issues/948
it is developers responsibility to invoke callback handler immediately while actually sending the request.
Could that be implemented please?

**Comment by ilcato** [comment]
Try 2.4.3
