### ISSUE TITLE
HC2 configuration problem

### ISSUE THREAD

**Issue by Damianod27** [ilcato/homebridge-Fibaro-HC2#210]
Hi.  I am new here.  I'm just starting my adventure with Homebridge.  I have already launched: Blebox, Tuya, Ewelink, Magic Home, Canbee 2 and Mqqt.  What is most important to me is the Fibaro HC2.  I don't want to act.  I can't handle it.  Can anyone help me ?

![image](https://user-images.githubusercontent.com/79320859/109228944-ec7e6800-77c2-11eb-9aa7-1d39779476ec.jpeg)

**Comment by ilcato** [comment]
It seems that the host param contains an IP address not existing.

**Comment by Damianod27** [comment]
Where am I making a mistake?

![image](https://user-images.githubusercontent.com/79320859/109303303-e9bf5980-783a-11eb-8062-f29e37b0a3bc.jpeg)

![image](https://user-images.githubusercontent.com/79320859/109303330-f04dd100-783a-11eb-813a-10fd4d1a63e3.png)

![image](https://user-images.githubusercontent.com/79320859/109303351-f643b200-783a-11eb-9b6b-97663b36be88.jpeg)

![image](https://user-images.githubusercontent.com/79320859/109303368-fba0fc80-783a-11eb-8335-e27c04eafbb4.jpeg)

**Comment by Damianod27** [comment]
Can the username be an e-mail?  Is it just the name itself?

**Comment by ilcato** [comment]
Are you able to 'ping' 192.168.8.173 from 192.168.8.171 ?

**Comment by Damianod27** [comment]
![image](https://user-images.githubusercontent.com/79320859/109345834-0bd3ce80-7871-11eb-9114-5ca4b0624829.png)

**Comment by ilcato** [comment]
@Damianod27, in your config.json file I see on line 21 a platform param that shouldn't be present.

**Comment by Damianod27** [comment]
This line of code creates itself when you save the configuration in the plugin.  I tried to delete in the main configuration file but there is an error.  Photos before and after.  I do not know what to do ?

![image](https://user-images.githubusercontent.com/79320859/109384988-d078e480-78f0-11eb-89e9-4977d3e7224d.png)

![image](https://user-images.githubusercontent.com/79320859/109384991-d373d500-78f0-11eb-9416-95ce6588fd5f.jpeg)

**Comment by ilcato** [comment]
Please, send me the entire config.json (without your credentials) please.

**Comment by Damianod27** [comment]
I bought a Raspberry Pi specifically for your plug.  My home automation up to 95% fibaro.  I will reward you, my friend, when we complete the matter.  Thank you for your help.  I will send the configuration right away

**Comment by Damianod27** [comment]
{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:17:CA:7B:7D:E3",
        "port": 51826,
        "pin": "279-27-279"
    },
    "accessories": [
        {
            "name": "Virtual Click",
            "genericswitch": true,
            "flip": false,
            "time": 1000,
            "accessory": "VirtualSwitch"
        },
        {
            "name": "Virtual Hold",
            "genericswitch": true,
            "flip": false,
            "time": 1000,
            "accessory": "VirtualSwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "blue",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "bridge": {
                "name": "Blebox",
                "username": "192.168.8.194",
                "port": 51826,
                "pin": "000-00-000"
            },
            "description": "Custom description",
            "platforms": [
                {
                    "platform": "BleBoxPlatform",
                    "name": "Blebox",
                    "NEXT_SCAN_DELAY_IN_MIN": 0
                }
            ],
            "accessories": [],
            "platform": "BleBoxPlatform"
        },
        {
            "name": "eWeLink",
            "countryCode": "48",
            "username": "damian.dobromilski@gmail.com",
            "password": "xxxxxxxxx",
            "mode": "auto",
            "disableDeviceLogging": false,
            "disablePlugin": false,
            "platform": "eWeLink"
        },
        {
            "platform": "MagicHome-Platform",
            "name": "MagicHome-Platform",
            "debug": false,
            "lights": [
                {
                    "name": "Pixel LED",
                    "ip": "192.168.8.179",
                    "setup": "RGB",
                    "purewhite": false,
                    "timeout": 10000
                },
                {
                    "name": "LED Tedee",
                    "ip": "192.168.8.169",
                    "setup": "RGB",
                    "purewhite": false,
                    "timeout": 10000
                }
            ]
        },
        {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Lampa Duplo",
                    "type": "outlet",
                    "manufacturer": "EZH",
                    "model": "Wifi Mini Smart Life Outlet",
                    "id": "011233455677899abbcd",
                    "key": "0123456789abcdef"
                },
                {
                    "name": "Fibaro Home Center 2",
                    "type": "outlet",
                    "manufacturer": "EZH",
                    "model": "Wifi Mini Smart Life Outlet",
                    "id": "011233455677899abbcd",
                    "key": "0123456789abcdef"
                }
            ]
        },
        {
            "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:40",
                "port": 51826,
                "pin": "279-00-279"
            },
            "description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",
            "platforms": [
                {
                    "platform": "FibaroHC2",
                    "name": "FibaroHC2",
                    "host": "192.168.8.173",
                    "username": "damian.dobromilski@gmail.com",
                    "password": "test123",
                    "pollerperiod": "2",
                    "securitysystem": "disabled"
                }
            ],
            "accessories": [],
            "platform": "FibaroHC2"
        },
        {
            "pruning": {
                "pruneMissingCachedAccessories": false,
                "restartsBeforeMissingAccessoriesPruned": 3,
                "pruneAllAccessoriesNextRestart": false
            },
            "whiteEffects": {
                "simultaniousDevicesColorWhite": true,
                "colorWhiteThreshold": 10,
                "colorWhiteThresholdSimultaniousDevices": 50,
                "colorOffThresholdSimultaniousDevices": 5
            },
            "deviceManagement": {
                "blacklistOrWhitelist": "blacklist"
            },
            "advancedOptions": {
                "namesWithMacAddress": false
            },
            "platform": "homebridge-magichome-dynamic-platform"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "groups": false,
            "hosts": [
                "192.168.8.171:4530"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": false,
            "resource": true,
            "sensors": true,
            "wallSwitch": true,
            "platform": "Hue"
        },
        {
            "name": "Alexa",
            "username": "homebridgeamazonalexa",
            "password": "xxxxxxx",
            "pin": "279-27-279",
            "routines": false,
            "blind": false,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "platform": "Alexa"
        }
    ],
    "disabledPlugins": [
        "homebridge-tuya-lan",
        "homebridge-magichome-platform"
    ]
}

**Comment by ilcato** [comment]
@Damianod27, there was a new bridge inside the definition of the platform (probably you selected the new option coming Fromm homebridge 1.3, I don't know). Anyway, the correct configuration should be the following:

`{
   "bridge":{
      "name":"Homebridge",
      "username":"0E:17:CA:7B:7D:E3",
      "port":51826,
      "pin":"279-27-279"
   },
   "accessories":[
      {
         "name":"Virtual Click",
         "genericswitch":true,
         "flip":false,
         "time":1000,
         "accessory":"VirtualSwitch"
      },
      {
         "name":"Virtual Hold",
         "genericswitch":true,
         "flip":false,
         "time":1000,
         "accessory":"VirtualSwitch"
      }
   ],
   "platforms":[
      {
         "name":"Config",
         "port":8581,
         "auth":"form",
         "theme":"blue",
         "tempUnits":"c",
         "lang":"auto",
         "platform":"config"
      },
      {
         "bridge":{
            "name":"Blebox",
            "username":"192.168.8.194",
            "port":51826,
            "pin":"000-00-000"
         },
         "description":"Custom description",
         "platforms":[
            {
               "platform":"BleBoxPlatform",
               "name":"Blebox",
               "NEXT_SCAN_DELAY_IN_MIN":0
            }
         ],
         "accessories":[
            
         ],
         "platform":"BleBoxPlatform"
      },
      {
         "name":"eWeLink",
         "countryCode":"48",
         "username":"damian.dobromilski@gmail.com",
         "password":"xxxxxxxxx",
         "mode":"auto",
         "disableDeviceLogging":false,
         "disablePlugin":false,
         "platform":"eWeLink"
      },
      {
         "platform":"MagicHome-Platform",
         "name":"MagicHome-Platform",
         "debug":false,
         "lights":[
            {
               "name":"Pixel LED",
               "ip":"192.168.8.179",
               "setup":"RGB",
               "purewhite":false,
               "timeout":10000
            },
            {
               "name":"LED Tedee",
               "ip":"192.168.8.169",
               "setup":"RGB",
               "purewhite":false,
               "timeout":10000
            }
         ]
      },
      {
         "platform":"TuyaLan",
         "devices":[
            {
               "name":"Lampa Duplo",
               "type":"outlet",
               "manufacturer":"EZH",
               "model":"Wifi Mini Smart Life Outlet",
               "id":"011233455677899abbcd",
               "key":"0123456789abcdef"
            },
            {
               "name":"Fibaro Home Center 2",
               "type":"outlet",
               "manufacturer":"EZH",
               "model":"Wifi Mini Smart Life Outlet",
               "id":"011233455677899abbcd",
               "key":"0123456789abcdef"
            }
         ]
      },
      {
         "platform":"FibaroHC2",
         "name":"FibaroHC2",
         "host":"192.168.8.173",
         "username":"damian.dobromilski@gmail.com",
         "password":"test123",
         "pollerperiod":"2",
         "securitysystem":"disabled"
      },
      {
         "pruning":{
            "pruneMissingCachedAccessories":false,
            "restartsBeforeMissingAccessoriesPruned":3,
            "pruneAllAccessoriesNextRestart":false
         },
         "whiteEffects":{
            "simultaniousDevicesColorWhite":true,
            "colorWhiteThreshold":10,
            "colorWhiteThresholdSimultaniousDevices":50,
            "colorOffThresholdSimultaniousDevices":5
         },
         "deviceManagement":{
            "blacklistOrWhitelist":"blacklist"
         },
         "advancedOptions":{
            "namesWithMacAddress":false
         },
         "platform":"homebridge-magichome-dynamic-platform"
      },
      {
         "name":"Hue",
         "anyOn":true,
         "effects":true,
         "groups":false,
         "hosts":[
            "192.168.8.171:4530"
         ],
         "lights":true,
         "nativeHomeKitLights":true,
         "nativeHomeKitSensors":false,
         "resource":true,
         "sensors":true,
         "wallSwitch":true,
         "platform":"Hue"
      },
      {
         "name":"Alexa",
         "username":"homebridgeamazonalexa",
         "password":"xxxxxxx",
         "pin":"279-27-279",
         "routines":false,
         "blind":false,
         "door":false,
         "debug":false,
         "deviceListHandling":"allow",
         "platform":"Alexa"
      }
   ],
   "disabledPlugins":[
      "homebridge-tuya-lan",
      "homebridge-magichome-platform"
   ]
}`

**Comment by Damianod27** [comment]
Wow Wow Wow Wow Wow
YOU ARE AMAZING !!!!!  
Thank you very much !!!

I installed Homebridge from the official website.  After entering the system, I did not set anything.  What was wrong in the configuration file.  I will know for the future as if I had put everything all over again.  

Where can I reward you?  Coffee GitHub or PayPal?

**Comment by Damianod27** [comment]
What should I change what parameters to give on the standard HC2 plugin?

**Comment by ilcato** [comment]
> What should I change what parameters to give on the standard HC2 plugin?

What do you mean?
