### ISSUE TITLE
2.4.2 Latest Fibaro HC2 Plugin global variables help

### ISSUE THREAD

**Issue by baduxiyang** [ilcato/homebridge-Fibaro-HC2#215]
When I press the global variable switch in apple family, the scene associated with the global variable in HC2 will not trigger to run. Please help to repair

**Comment by ilcato** [comment]
@Krillle, can you help with this. May it depends on your PR? I cannot test anymore on HC2.

**Comment by Krillle** [comment]
@baduxiyang The latest pull request enables to set global variables even while using not admin rights users, e.g. to restrict access to devices. However it should not break your running setup. Lets check out what the problem might be:

Does the global variable in Home Center 2 change to true and false, if you switch the switch in home app?
 
Are you using admin user of Home Center 2 in config.json? → If not you will see the log entry "There was a problem setting variable:  xxx to true"

Did you set a admin user explicitly in plugin settings or config.json? 
```
    "adminUsername": "homecenteradmin",
    "adminPassword": "adminpassword",

```

**Comment by baduxiyang** [comment]
@Krillle  @ilcato Thanks , I will try again tomorow!
