### ISSUE TITLE
Error from CO Sensor

### ISSUE THREAD

**Issue by redeemer666** [ilcato/homebridge-Fibaro-HC2#220]
Hi ilcato,

Si è 1.3, my Fibaro CO Sensor send this error:

[homebridge-fibaro-hc2] This plugin generated a warning from the characteristic 'Carbon Monoxide Peak Level': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.

Not a big hassle, just to understand what’s going on.

Thanks

**Comment by ilcato** [comment]
@redeemer666  Try 2.4.3

**Comment by redeemer666** [comment]
Hi ilcato. Unfortunately the error remain...
