### ISSUE TITLE
I can't see devices

### ISSUE THREAD

**Issue by Damianod27** [ilcato/homebridge-Fibaro-HC2#224]
Hello. I accidentally found a bug.  I had to remove the wall plug from HC2.  I restarted it to factory settings (Wall Plug).  I added back to HC2.  He has not been in Homebridge since then.  I tried the same thing with another Wall Plug and the situation is the same.  What could be the reason?  

I also installed a clean Homebridge on another device and your plug, the situation is the same, i.e. you cannot see these devices

Homebridge : 1.3.4
Homebridge UI : 4.41.0
FIBARO HC2 : 4.600

Best Regards 
Damian

**Comment by ilcato** [comment]
Are you able to list it via the REST API?

**Comment by Damianod27** [comment]
Does not understand.  What is Rest Api?  It is normally visible in HC2 and in the Home Center Application.  If he installs HC2 directly in Amazon Alexa is also visible.  Works as normal as always.  It is not only visible in homebridge as well as in HomeKit

![image](https://user-images.githubusercontent.com/79320859/113887060-760d5680-97c1-11eb-8bee-a06acfdfe3be.jpeg)

**Comment by ilcato** [comment]
@Damianod27, connect to http://<Home Center IP-address>/docs/
and select devices section and GET device and specify the ID of the devices.

**Comment by Damianod27** [comment]
I'm sorry but I never did.  I have no idea how it is done or what it is about 😟

**Comment by ilcato** [comment]
@Damianod27 replace <Home Center IP-address> with the same IP you configured in the plugin, and open a browser at this URL.

**Comment by Damianod27** [comment]
Thank you.  Was it about?

![image](https://user-images.githubusercontent.com/79320859/113911814-b4633f80-97da-11eb-894e-1217a526f581.jpeg)

**Comment by Damianod27** [comment]
{
  "id": 199,
  "name": "198.0",
  "roomID": 0,
  "type": "com.fibaro.FGWP102",
  "baseType": "com.fibaro.FGWP",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 198,
  "remoteGatewayId": 0,
  "interfaces": [
    "deviceGrouping",
    "energy",
    "fibaroFirmwareUpdate",
    "light",
    "power",
    "zwave",
    "zwaveAlarm",
    "zwaveMultiChannelAssociation"
  ],
  "properties": {
    "parameters": [
      {
        "id": 1,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 2,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 3,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 2,
        "value": 0
      },
      {
        "id": 10,
        "lastReportedValue": 80,
        "lastSetValue": 80,
        "size": 1,
        "value": 80
      },
      {
        "id": 11,
        "lastReportedValue": 15,
        "lastSetValue": 15,
        "size": 1,
        "value": 15
      },
      {
        "id": 12,
        "lastReportedValue": 30,
        "lastSetValue": 30,
        "size": 2,
        "value": 30
      },
      {
        "id": 13,
        "lastReportedValue": 10,
        "lastSetValue": 10,
        "size": 2,
        "value": 10
      },
      {
        "id": 14,
        "lastReportedValue": 3600,
        "lastSetValue": 3600,
        "size": 2,
        "value": 3600
      },
      {
        "id": 15,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 20,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 21,
        "lastReportedValue": 300,
        "lastSetValue": 300,
        "size": 2,
        "value": 300
      },
      {
        "id": 22,
        "lastReportedValue": 500,
        "lastSetValue": 500,
        "size": 2,
        "value": 500
      },
      {
        "id": 23,
        "lastReportedValue": 6,
        "lastSetValue": 6,
        "size": 1,
        "value": 6
      },
      {
        "id": 24,
        "lastReportedValue": 255,
        "lastSetValue": 255,
        "size": 2,
        "value": 255
      },
      {
        "id": 30,
        "lastReportedValue": 63,
        "lastSetValue": 63,
        "size": 1,
        "value": 63
      },
      {
        "id": 31,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 32,
        "lastReportedValue": 600,
        "lastSetValue": 600,
        "size": 2,
        "value": 600
      },
      {
        "id": 40,
        "lastReportedValue": 25000,
        "lastSetValue": 25000,
        "size": 2,
        "value": 25000
      },
      {
        "id": 41,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 42,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 43,
        "lastReportedValue": 2,
        "lastSetValue": 2,
        "size": 1,
        "value": 2
      },
      {
        "id": 50,
        "lastReportedValue": 3,
        "lastSetValue": 3,
        "size": 1,
        "value": 3
      }
    ],
    "pollingTimeSec": 0,
    "zwaveCompany": "Fibargroup",
    "zwaveInfo": "3,4,5",
    "zwaveVersion": "3.2",
    "alarmLevel": "0",
    "alarmType": "0",
    "categories": "[\"lights\"]",
    "color": "white",
    "configured": true,
    "dead": "false",
    "deadReason": "",
    "deviceControlType": "2",
    "deviceGroup": "[]",
    "deviceGroupMaster": "0",
    "deviceIcon": "125",
    "emailNotificationID": "0",
    "emailNotificationType": "0",
    "endPointId": "0",
    "energy": "0.00",
    "firmwareUpdate": "{\"status\":\"UpToDate\",\"updateVersion\":\"\"}",
    "icon": "{\"path\":\"fibaro/icons/com.fibaro.FGWP_EU/plug1.png\",\"source\":\"HC\"}",
    "isLight": "true",
    "log": "",
    "logTemp": "",
    "manufacturer": "",
    "markAsDead": "true",
    "model": "",
    "nodeId": "48",
    "parametersTemplate": "741",
    "power": "0.00",
    "productInfo": "1,15,6,2,16,1,3,2",
    "pushNotificationID": "0",
    "pushNotificationType": "0",
    "remoteGatewayId": "0",
    "saveLogs": "true",
    "serialNumber": "h'00000000000198ec",
    "showEnergy": "true",
    "smsNotificationID": "0",
    "smsNotificationType": "0",
    "updateVersion": "",
    "useTemplate": "true",
    "userDescription": "",
    "value": "true"
  },
  "actions": {
    "abortUpdate": 1,
    "reconfigure": 0,
    "reset": 0,
    "retryUpdate": 1,
    "startUpdate": 1,
    "turnOff": 0,
    "turnOn": 0,
    "updateFirmware": 1
  },
  "created": 1617817784,
  "modified": 1617817784,
  "sortOrder": 179
}

**Comment by ilcato** [comment]
@Damianod27, it seems correct.
Two things:
1. is there some error in homebridge logs?
2. Is the Home Center user you set in config.json allowed to see these device?

**Comment by Damianod27** [comment]
1. There are no errors in Homebridge logs (I checked several times) 
2. I don't have any locks in the settings.  

It only happened when I removed the WALL Plug from HC2.  I have hard reset WALL Plug to factory settings.  After separating from HC2 again, I cannot see it in Homebridge.  I did a trial with the second WALL Plug and the same.  At the moment, Homebridge does not see two Wall Plugs.

**Comment by Damianod27** [comment]
Homebridge runs on Raspberry Pi 4. I also have BananaPi M2 Quad-Core and Raspberry Pi Zero.  I put a completely clean Homebridge on them and installed your plugin.  Both have the same problem.  I can't see the two WALL Plugs I have removed.

**Comment by ilcato** [comment]
2. Are you using the same user as the main home center user?

**Comment by Damianod27** [comment]
I do not have a special Homebridge-only account.  I didn't think tomorrow, I will check my main account and let me know.

**Comment by Damianod27** [comment]
I checked.  Works on a different account.  Two removed Wall Plugs are shown.  If the first account is returned, the same problem is the lack of two Wall Plugs.  Thank you.  I need to log in to a different account.
