### ISSUE TITLE
How to remove single Fibaro accessory from HomeKit setup

### ISSUE THREAD

**Issue by leoneleone** [ilcato/homebridge-Fibaro-HC2#23]
Hello,

Is there any way to remove a single Fibaro configured accessory from my HomeKit setup. 
I presume if the accessory/device is removed from .homebridge/Accessories files and the persist files that should give me what I need. But how to pinpoint the relevant info from the files? 
Is there an easier way to remove the single accessory like I described?

Many Thanks

**Comment by ilcato** [comment]
If you deleted a device from home center (or made it not available to the user) the only way to update  homebridge plugin is for now to delete accessories folder and re run homebrige.
With the plugin 2.0 api there's the option to manage it automatically but I did not completely implemented it.

**Comment by leoneleone** [comment]
@ilcato
Thanks for the info. Deleting the accessories folder should effect my HomeKit configuration or create duplicates? 
Does this also remove the accessory from the persist folder? 
Double checking before I try it

**Comment by ilcato** [comment]
HomeKit db is upgraded correctly, no dup. No need to change persist folder.

**Comment by leoneleone** [comment]
Thanks for your help!! 😀
