### ISSUE TITLE
Where to place the Config.json ? 

### ISSUE THREAD

**Issue by viperNOR** [ilcato/homebridge-Fibaro-HC2#24]
Hi.

The sample file is under 
usr/local/.homebridge/ or
usr/local/lib/node_modules/homebridge , 
but from the instructions it might be that we should place it under 
home/pi/.homebridge/

**Comment by ilcato** [comment]
The config.json file on a raspberry must be put into a .homebridge folder on the home user folder; by default /home/pi/.homebridge
