### ISSUE TITLE
No negative temperatures

### ISSUE THREAD

**Issue by astrandb** [ilcato/homebridge-Fibaro-HC2#26]
I have a temperature probe in a freezer (approx -20 C). No value is displayed in the Home app. I have googled around and found that "characteristic.Props.minValue" should be set to e.g. -50 in order to allow negative values for temperatures. Since my knowledge in JavaScript is very limited I need your help.
The winter is coming soon to Sweden so it I appreciate a fix if possible.

**Comment by ilcato** [comment]
Try this: replace the index.js file with the following [link](https://raw.githubusercontent.com/ilcato/homebridge-Fibaro-HC2/master/index.js)

**Comment by astrandb** [comment]
It works! Thank you.

**Comment by ilcato** [comment]
I will insert it un the next release.
