### ISSUE TITLE
Zipato RGBW support

### ISSUE THREAD

**Issue by gjniewenhuijse** [ilcato/homebridge-Fibaro-HC2#28]
Hello,

My HCL support the Zipato RGBW bulb, but this device is not loaded in the homebridge plugin.

Can you please add support for this device.

**Comment by ilcato** [comment]
I have such a bulb and it shows correctly in homebridge.
Which version do you have?

**Comment by gjniewenhuijse** [comment]
Now i see my device when i add in the config:
"grouping": "none"

But is it normal that i need to set my blue color > 0, else other colors didn't work (it Always shows cold white). Also in fibaro. I know this is not a homebridge question, but you have also this device

**Comment by ilcato** [comment]
No idea. Sorry
