### ISSUE TITLE
Fibaro Smoke alarm and Heat Detector not showing up

### ISSUE THREAD

**Issue by BilboSwagginz** [ilcato/homebridge-Fibaro-HC2#29]
Hello,

My Fibaro Smoke alarm and Heat Detector doesn't show up in HomeKit, i guess it's just because the plugin doesn't recognize it. I would also like to know if there is a way for me to try, and implement support on devices, that isn't supported? Like does it create some kind of debug file, with information when it fails to implement a device?

Thank you,
- Bilbo Swagginz

**Comment by ilcato** [comment]
Yes, I'm currently not supporting them. Let's wait some weeks and see if Fibaro will add an official support for homekit on existing hc2 before investing more effort in this project. If they will provide suppport only on a new hc3 machine I will extend functionalities of the plugin.

**Comment by MAM78** [comment]
Do you now support the heatDetector ?

**Comment by ilcato** [comment]
The [Fibaro Smoke Detector](https://www.fibaro.com/en/products/smoke-sensor/) is supported.

**Comment by MAM78** [comment]
When loading devices into the Home app on iOS. I realize that I miss some parts.

For the FGSD-002, I see only the following:

- Temperature sensor
- Smoke detection sensor

I do not see the fire detection sensor (heatDetector) under homekit.

An idea of the problem ?

**Comment by MAM78** [comment]
Is it also possible to give me an answer to my last message on the site www.domotique-fibaro.fr about your Ilcato Tollkit.

Here is the link :

https://www.domotique-fibaro.fr/topic/5479-commander-lhc2-et-hcl-via-homekit-et-siri/?page=31#comment-172027

**Comment by ilcato** [comment]
@mam78 there’s no heat detector sensor in HomeKit.

No idea why the app doesn’t work for you.

**Comment by MAM78** [comment]
@ilcato Ok thanks
