### ISSUE TITLE
Door state inverted

### ISSUE THREAD

**Issue by marcvoumard** [ilcato/homebridge-Fibaro-HC2#32]
The door is marked as closed when it's open, and as open when it's closed...

FIbaro door/window sensor

Thank's for your help

**Comment by BilboSwagginz** [comment]
I had that problem too but read in the read-me that it has been fixed in version 0.7.0 and the version on NPM is only 0.6.9 so replace the index.js with https://github.com/ilcato/homebridge-Fibaro-HC2/blob/master/index.js

**Comment by ilcato** [comment]
Just published version 0.7.0
