### ISSUE TITLE
Duplicated items in HomeKit

### ISSUE THREAD

**Issue by tkaudioservices** [ilcato/homebridge-Fibaro-HC2#34]
I have duplicated items in my home kit, is there a file/database in the file structure where I would find these so I can delete the duplicates?

**Comment by ilcato** [comment]
remove the accessories folder and restart homebridge

**Comment by tkaudioservices** [comment]
Perfect, I found that I needed to also delete the persist folder.

**Comment by ilcato** [comment]
If you delete persist folder you need to delete accessory on iOS and re associate homebridge

**Comment by tkaudioservices** [comment]
yeh yeh, that's exactly what I have done, however some items that did appear before, no longer appear. I guess the same concept would also be, when new devices are added to Fibaro, would Raspberry Pi need to be rebooted in order for the new devices to show up in HomeKit?

**Comment by ilcato** [comment]
yes

**Comment by tkaudioservices** [comment]
So what would cause some devices to be missing?

**Comment by ilcato** [comment]
strange. what kind of devices are no more visible?

**Comment by tkaudioservices** [comment]
The Fibaro RGB controller

**Comment by ilcato** [comment]
Is it still present in home center?

**Comment by tkaudioservices** [comment]
Yes, plus I can control in the Home Center no problem

**Comment by tkaudioservices** [comment]
I am wondering if HomeKit isn't loading correctly because of an error. When I run home kit from terminal I get this error. 

`Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d281603f-5c58-4530-970b-58899583e2cf
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:222:13)
    at Server._configCachedPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:345:18)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)`

Thanks you for your help

**Comment by ilcato** [comment]
you have two or more accessories with the same name in the same room.

**Comment by tkaudioservices** [comment]
naming the devices correctly solved all the problems. Thank you.

In the config.json, what is the difference between rooms and none?

**Comment by ilcato** [comment]
If you set the parameter to room homebridge will create a single homekit accessories for each room containing all the devices in the room.
