### ISSUE TITLE
Changes to virtual devices not updated

### ISSUE THREAD

**Issue by NookyDo** [ilcato/homebridge-Fibaro-HC2#35]
Hi together,

I am using homebridge on Raspberry 3 B and together with the Fibaro HC2 Plugin.

It all works great. All devices (sensors etc) are added and included perfectly.
In example virtuall devices with multiple buttons are included as single devices (one for each button / function) which is fine.

But:
If i change an devlice (for example if i add a button / funktion to a virtual device) there seems to be no chance to get this into homebridge and Apple Home app.

It does not show up as new device.
Maybe the reason is, that an existing device is not / never checked again after it has been added once?

Or is there a trick how to do that?

thank you / regards

**Comment by ilcato** [comment]
delete accessories folder and restart homebridge

**Comment by NookyDo** [comment]
does this delete all accessories? So all configurations and maybe scenes are gone that I already made in the home app?

**Comment by ilcato** [comment]
No, the folder is only a cache.

**Comment by NookyDo** [comment]
I tried that - but now in the App (Apple Home App) all devices are gone - everything is empty now - what can I do?

**Comment by NookyDo** [comment]
problem seems to be that homebridge does not start anymore now.. it stopps at:

[2016-10-11 11:07:51] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ xxxxxx
    └────────────┘

Plugin - DidFinishLaunching
[2016-10-11 11:07:51] [FibaroHC2] Fetching Fibaro Home Center rooms ...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)

**Comment by ilcato** [comment]
You have another instance of homebridge running (EADDRINUSE: Address in use).
Stop it and relaunch homebridge.

**Comment by NookyDo** [comment]
ok understand - that this is not the reason for the empty app..

because I restarted the rasperry several times (and so also the homebridge) and the app (and the accessory folder) now stays empty

Du you have an idea?

**Comment by NookyDo** [comment]
oh stopp - now it was filled and everything is back again - somehow it needed to start 3 times..

But all configurations are gone now..
All devices are in "standardroom" now and not anymore in the configured rooms.. and all scenes of the homekit app are also gone..

**Comment by ilcato** [comment]
for importing the rooms and the association with devices use the iOs app: ilcato toolkit on the App Store.

**Comment by NookyDo** [comment]
ok but als the scenes that I had defined within the Appe Home app - they are gone now since I deleted the accessories folder?

**Comment by NookyDo** [comment]
..and if so (if they are gone now and I have to redefine them again) - what is the best solution for next time when i change something to a virtual device? To get these changes into the homekit?
Is there a better solution than deleting the accessory folder which also destroys the whole room setup and deletes all homekit scenes?

**Comment by ilcato** [comment]
Deleting the accessories folder should not destry the room setup and homekit scenes. Try it again please.

**Comment by ilcato** [comment]
with a simple scenario

**Comment by NookyDo** [comment]
it somehow seems to be a problem in combination with the IOS10 native HOME app.. the scenes are lost there. 
I also added a new button to an existing virtual device - even with deleting the accessories folder and restarting, it does not show up in the Home app

But in other Apps like "Eve" the news buttos does show up correctly - and also the lost scenes are still available there.. but not in the Apple Home app.. strange.. any idea?

There should not be any difference between the devices and scenes shown in different apps - right?

The new button of the virtual device shows up in EVE but does not show up in HOME and also does not show up in your Ilcato Toolkit

**Comment by ilcato** [comment]
Are you on iOs 10.0.1?

**Comment by NookyDo** [comment]
No - on 10.0.2

**Comment by ilcato** [comment]
I'm on 10.0.1 and it works as expected.

**Comment by NookyDo** [comment]
have you tried to:

- Ad a virtual device to Fibaro and Add a button "Test 1"
- import that device to HOME App - so you will see a device "Test 1"
- define some scene-activities in HOME App
- in Fibaro add a second button to that same virtual device - just add a second button "test 2"
- try to import it into HOME app - it will not show up (but it shows up in other apps)
- delete "Accessory" Folder..
- restart HomeBridge
- now it might show up - but also might not.. in most cases it might not.. and maybe all scenes are lost - and also the room connection..

Can you reproduce that?

regards

**Comment by ilcato** [comment]
will test tonight

**Comment by NookyDo** [comment]
Found out something more which might help you to debug all this - this seems to be the issue why the homeKit Scenes (created in the Apps) show in some apps and in some not:

Your process of deleting the Accessory-Folder seems to create new IDs for each device on HomeKit / App Side (or maybe even in the Bridge / Plugin?)

Thats why the App Scenes are still there (existing), but no more actions (device + action) is linked to them. The scenes are now empty without function.

And these empty scenes semm to be handeled different from different apps. The App "eve" still shows them and you can assign new actions to them.
But the Appe HOME app seems to not show empty scenes anymore - thats why I was not able to find them there.. 
After using "Eve" to asign devices with actions again to the old scenes, they do appear in apple HOME again. 

So this explains why scenes disapear in the own app but not in the other app.

But question still is: why do all devices get new IDs or do get unlinked from scenes and rooms when the Accessories Folder was deleted?

And isn't there a better way to get changes of virtual devices into the homebridge?
Like scanning all devices for changes on homebridge startup - so after changes, it is enough to restart homebridge? And to make sure devices are not updated by deleting the old once and creating new once but updating the existing once so they do not get unlinked from the rooms and scenes..

hope to help you somehow with my explanations - great work with that plugin!!
regards

**Comment by ilcato** [comment]
Found a bug in the plugin.
It should find new or modified accessory only by restarting homebridge. No need to delete accessories folder.
It is correct that removing accessories folders new id are generated for existing accessories with all the implication that you described.
Will try to fix the bug asap.

**Comment by ilcato** [comment]
@NookyDo, I think I have fixed the bug and complete the mechanism that allows to automatically update adding, removing and modifying accessories from HC2 without corrupting homekit database.
Do you mind testing the new version ? It's [here](https://raw.githubusercontent.com/ilcato/homebridge-Fibaro-HC2/master/index.js).
Thanks

**Comment by NookyDo** [comment]
@ilcato OK no problem - what exactly do I have to do to do the update?

Download the index.js and replace it in the raspery and reboot? Or anything else? 
Can you please write what and where (path) I exactly have to do / replace? Just to be sure to do nothing wrong :)

**Comment by ilcato** [comment]
Yes, replace the file and restart homebridge.
The path is: /usr/lib/node_modules/homebridge-fibaro-hc2 or /usr/local/lib/node_modules/homebridge-fibaro-hc2

**Comment by NookyDo** [comment]
Hi @ilcato 
bringing in new devices and update during reboot works fine if the devices are new.. great!

But it still seems as if updated devices are nor recognised.

So if we create a new virtual device (i.e. with botton "open" and button "close") it shows up in HOME after reboot. Thats perfect.

But if I edit this device in fibaro and add a third button "TEST" and reboot the raspberry, the button "TEST" does not show up.

Can you please test this?

**Comment by ilcato** [comment]
I tried it and it works for me by killing the iOs app and restarting it.

**Comment by NookyDo** [comment]
Now on the second trial it does not work at all - even after several reboots.. I added an "slider" to a virtual device..
All devices show "no connection" - seems as if homebridge is not running anymore..
is there an errorlog I can use to see whats wrong? Can you please post the whole command to show / view that errorlog?

**Comment by ilcato** [comment]
The error log position depends on how do you run homebridge. Are you starting automatically at boot time ?

**Comment by NookyDo** [comment]
yes I do..

**Comment by ilcato** [comment]
So you specify where the error log is in the startup script. Normally it's in the .homebridge folder

**Comment by ilcato** [comment]
I retried the use case you mentioned and it works.

**Comment by ilcato** [comment]
Were you able to find the log?

**Comment by NookyDo** [comment]
Hi @ilcato  sorry for the late replay..

It was some work to get the starting script working with a defined errorlog.. my first script was without error output..

So this is the error I always get now during startup:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour com$
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 15c8d453-9bec-466a-907d-65be0a881cb1
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222:13)
    at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:345:18)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by ilcato** [comment]
It seems a problem with the "migration" of the old accessory cache. Can you test on a clean base?

**Comment by NookyDo** [comment]
@ilcato if I now delete the accessories cache it throws the following error:

[2016-10-24 17:20:21] Loading 1 platforms...
[2016-10-24 17:20:21] [FibaroHC2] Initializing FibaroHC2 platform...
[2016-10-24 17:20:22] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ xxxxxxxxxxxxxxxxx │
    └────────────┘

Plugin - DidFinishLaunching
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)

**Comment by ilcato** [comment]
You have homebridge already running: EADDRINUSE
You need to kill it before running it again.

**Comment by NookyDo** [comment]
OK after a complete re-installation (uninstall and install of your plugin - copying the new index) I gut it running again..

But update of devices does still not work..

If I add a new button on an existing and integrated virtual device, it does not show up after rebooting the raspberry..

**Comment by ilcato** [comment]
I made this test:

- created a virtual device with 2 buttons in Home Center
- restarted homebridge --> the device appears on the HomeKit apps (Native iOs 10 Home app, and a few others)
- added a button on the same virtual device as before
- restarted homebridge --> the device appears updated on the HomeKit apps (with the new button), no need to kill and start the apps
- removed the same button 
- restarted homebridge --> the device appears updated on the HomeKit apps (without the third button)


How do you start homebridge?
Which version of node.js do you have?
Which version of homebridge do you have?
