### ISSUE TITLE
Add new device on home kit

### ISSUE THREAD

**Issue by nrm83** [ilcato/homebridge-Fibaro-HC2#38]
Hi,

I just add new devices on my Fibaro home center2, how can update device on homebridge for the homekit add it on iphone ?

**Comment by ilcato** [comment]
With the current version you need to cancel accessories folder and restart homebridge. With the new one (currently under testing) you only need to restart homebridge.

**Comment by ilcato** [comment]
Simply update the index.json file on your installation with the current master one on this repository.

**Comment by nrm83** [comment]
Hi,
I can test if you want
Regards,

Nicolas





On Fri, Oct 21, 2016 at 11:26 AM +0200, "ilcato" <notifications@github.com> wrote:












With the current version you need to cancel accessories folder and restart homebridge. With the new one (currently under testing) you only need to restart homebridge.

**Comment by ilcato** [comment]
Please,  have a test

**Comment by nrm83** [comment]
Hi for me he work perfectly for the moment

**Comment by ilcato** [comment]
have you tried the scenario described [here](https://github.com/ilcato/homebridge-Fibaro-HC2/issues/35)?

**Comment by ilcato** [comment]
closing
