### ISSUE TITLE
How to pass two arguments?

### ISSUE THREAD

**Issue by Oxystin** [ilcato/homebridge-Fibaro-HC2#39]
Hi, ilcato! I use fibaro-homebridge plugin. He is amazing.
I'm trying to edit their own code to support my thermostat (remotec zxt-120). But faced with difficulties. I need to send to fibaro command that includes two arguments (setThermostatMode "TargetTemp", "Mode"). You have only one argument passed to the code.

**this.command("setThermostatMode", arg1  _[+ arg2 ???]_ , service, IDs);**         

Is it possible to pass two arguments?

**Comment by ilcato** [comment]
You can modify it maintaining the retro compatibility. Please propose a pull request.
