### ISSUE TITLE
Thermostat Secure SRT321 not reconized

### ISSUE THREAD

**Issue by Devil00303** [ilcato/homebridge-Fibaro-HC2#45]
Hi,

I've installed homebridge for HC2 and it's really good, but my thermostat Secure SRT321 wasn't reconized in iOS hom app.
In my fibaro, for this item I have this information (if that can help you) :
Genre:com.fibaro.thermostatHorstmann
Fabricant:Horstmann Controls Limited
Version:6.0
Parameters template:43
Type de protocole Z-Wave:2
[id-0059-0001-0003-06-00-Horstmann Controls Limited-.zip](https://github.com/ilcato/homebridge-Fibaro-HC2/files/689450/id-0059-0001-0003-06-00-Horstmann.Controls.Limited-.zip)

Best regards,

**Comment by ilcato** [comment]
@Devil00303, I created a support for such a thermostat in a previous version of the plugin. Probably something is changed in the current version of Home Center but without a physical device to test it's to difficult and time consuming for me to continue to support it.
If someone is able to provide me such a device I can more easily support it.

**Comment by vvsokolov** [comment]
I have the same issue: Secure SRT321 wasn't reconized in iOS Home app.
@ilcato , i can give you direct VPN access to Fibaro HCL with registered Secure SRT321.
May it be helpful ?

**Comment by Devil00303** [comment]
@ilcato Thank you for your quick answer :)
I'm in France, I'm not sure that I can provide to you an Secure SRT321 easily.
How can I help you for distant debug ?

@vvsokolov Thank you for your help if you can provide a access and if it is usefull :)

I see that have a new issue about danfoss thermostat, may be the last fibaro update (v4.110) make changes wich generate a bug for many thermostats ?

**Comment by ilcato** [comment]
Version 1.0.5 solve the issue
