### ISSUE TITLE
Thermostat Danfoss not recognized

### ISSUE THREAD

**Issue by vvsokolov** [ilcato/homebridge-Fibaro-HC2#46]
Hi, @ilcato !
Danfoss (014G0013 aka LC13) thermostats is not recognized.
In Fibaro HCL it visible as:
Device kind:Thermostat
Producer:Danfoss
Version:1.1
Parameters template:322
[id-0002-0005-0004-01-01-Danfoss-.zip](https://github.com/ilcato/homebridge-Fibaro-HC2/files/689772/id-0002-0005-0004-01-01-Danfoss-.zip)

**Comment by ilcato** [comment]
@vvsokolov, sure having access to your device may be useful.
In the mean time try to send me results of:

`http://HC_IP/api/devices/DEVICE_ID`

where:

HC_IP is the IP address of your Home Center and
DEVICE_ID is the Home Center ID of your device.

**Comment by vvsokolov** [comment]
{"id":62,"name":"Термостат","roomID":2,"type":"com.fibaro.thermostatHorstmann","baseType":"com.fibaro.thermostatDanfoss","enabled":true,"visible":true,"isPlugin":false,"parentId":61,"remoteGatewayId":0,"interfaces":["battery","zwave","zwaveConfiguration","zwaveWakeup"],"properties":{"parameters":[{"id":1,"lastReportedValue":129,"lastSetValue":129,"size":1,"value":129},{"id":2,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":3,"lastReportedValue":10,"lastSetValue":10,"size":1,"value":10}],"zwaveCompany":"Horstmann Controls Limited","zwaveInfo":"2,2,78","zwaveVersion":"6.0","wakeUpTime":600,"pollingTimeSec":0,"batteryLevel":"83","batteryLowNotification":"true","configured":"true","dead":"false","defInterval":"0","deviceControlType":"0","deviceIcon":"39","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","liliOffCommand":"","liliOnCommand":"","log":"","logTemp":"","manufacturer":"","markAsDead":"true","maxInterval":"0","minInterval":"0","model":"","nodeId":"20","parametersTemplate":"43","productInfo":"0,89,0,1,0,3,6,0","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","stepInterval":"0","targetLevel":"22.00","timestamp":"1483970374","unit":"C","useTemplate":"true","userDescription":"","value":"22.00"},"actions":{"getParameter":1,"reconfigure":0,"setInterval":1,"setParameter":2,"setTargetLevel":1,"setTime":1},"created":1483810149,"modified":1483810149,"sortOrder":10}

**Comment by ilcato** [comment]
Seems correct.
Can you send me the Homebridge log for the start process?

**Comment by vvsokolov** [comment]
ups, sorry, it was results for Horstmann thermostat!
It is not recognized too.
I will send you Homebridge log for both cases.

**Comment by R-TEMI** [comment]
Same issue here. 3 danfoss thermostats not detected at all.

**Comment by BilboSwagginz** [comment]
#25

**Comment by ilcato** [comment]
Version 1.0.5 solve the issue

**Comment by R-TEMI** [comment]
I still have the issue even after update.

{"id":18,"name":"Thermostat Sleeping","roomID":4,"type":"com.fibaro.thermostatDanfoss","baseType":"com.fibaro.hvac","enabled":true,"visible":true,"isPlugin":false,"parentId":17,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["battery","zwave","zwaveProtection","zwaveWakeup"],"properties":{"batteryLevel":80,"pollingTimeSec":0,"wakeUpTime":900,"zwaveCompany":"Danfoss","zwaveInfo":"6,3,67","zwaveVersion":"1.1","RFProtectionState":"0","RFProtectionSupport":"0","batteryLowNotification":"true","configured":"true","dead":"false","defInterval":"0","deviceControlType":"0","deviceIcon":"34","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","liliOffCommand":"","liliOnCommand":"","localProtectionState":"0","localProtectionSupport":"5","log":"","logTemp":"","manufacturer":"","markAsDead":"true","maxInterval":"0","minInterval":"0","model":"","nodeId":"5","parametersTemplate":"322","productInfo":"0,2,0,5,0,4,1,1","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","stepInterval":"0","targetLevel":"20.00","timestamp":"1485875356","unit":"C","useTemplate":"true","userDescription":"","value":"20.00"},"actions":{"reconfigure":0,"setInterval":1,"setTargetLevel":1,"setTime":1},"created":1485113161,"modified":1485113161,"sortOrder":9},{"id":29,"name":"Thermostat Right","roomID":4,"type":"com.fibaro.thermostatDanfoss","baseType":"com.fibaro.hvac","enabled":true,"visible":true,"isPlugin":false,"parentId":28,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["battery","zwave","zwaveProtection","zwaveWakeup"],"properties":{"batteryLevel":55,"pollingTimeSec":0,"wakeUpTime":900,"zwaveCompany":"Danfoss","zwaveInfo":"6,3,67","zwaveVersion":"1.1","RFProtectionState":"0","RFProtectionSupport":"0","batteryLowNotification":"true","configured":"true","dead":"false","defInterval":"0","deviceControlType":"0","deviceIcon":"34","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","liliOffCommand":"","liliOnCommand":"","localProtectionState":"0","localProtectionSupport":"5","log":"","logTemp":"","manufacturer":"","markAsDead":"true","maxInterval":"0","minInterval":"0","model":"","nodeId":"9","parametersTemplate":"322","productInfo":"0,2,0,5,0,4,1,1","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","stepInterval":"0","targetLevel":"20.00","timestamp":"1485875356","unit":"C","useTemplate":"true","userDescription":"","value":"20.00"},"actions":{"reconfigure":0,"setInterval":1,"setTargetLevel":1,"setTime":1},"created":1485113161,"modified":1485113161,"sortOrder":10},{"id":31,"name":"Thermostat Left","roomID":4,"type":"com.fibaro.thermostatDanfoss","baseType":"com.fibaro.hvac","enabled":true,"visible":true,"isPlugin":false,"parentId":30,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["battery","zwave","zwaveProtection","zwaveWakeup"],"properties":{"batteryLevel":41,"pollingTimeSec":0,"wakeUpTime":900,"zwaveCompany":"Danfoss","zwaveInfo":"6,3,67","zwaveVersion":"1.1","RFProtectionState":"0","RFProtectionSupport":"0","batteryLowNotification":"true","configured":"true","dead":"false","defInterval":"0","deviceControlType":"0","deviceIcon":"34","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","liliOffCommand":"","liliOnCommand":"","localProtectionState":"0","localProtectionSupport":"5","log":"","logTemp":"","manufacturer":"","markAsDead":"true","maxInterval":"0","minInterval":"0","model":"","nodeId":"10","parametersTemplate":"322","productInfo":"0,2,0,5,0,4,1,1","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","stepInterval":"0","targetLevel":"20.00","timestamp":"1485875356","unit":"C","useTemplate":"true","userDescription":"","value":"20.00"},"actions":{"reconfigure":0,"setInterval":1,"setTargetLevel":1,"setTime":1},"created":1485113162,"modified":1485113162,"sortOrder":11},{"id":36,"name":"iOS_Temp","roomID":4,"type":"virtual_device","visible":true,"enabled":true,"properties":{"deviceIcon":0,"ip":"10.0.7.2","port":80,"log":"","logTemp":"","currentIcon":"0","log":"","logTemp":"","mainLoop":"","visible":"true","rows":[{"type":"button","elements":[{"id":1,"lua":false,"waitForResponse":true,"caption":"22C","name":"Temp","empty":false,"msg":"GET /api/sceneControl?id=10&action=start HTTP/1.10x0D0x0AHost: 10.0.7.20x0D0x0AAuthorization: Basic cGk6VFh1d2lZQ0ZyemhnaXJZdW9rTjI=0x0D0x0A0x0D0x0A","buttonIcon":0,"favourite":false,"main":true}]}]},"actions":{"pressButton":1,"setSlider":2,"setProperty":2},"created":1485113163,"modified":1485113163,"sortOrder":12}]

**Comment by raffoul** [comment]
It works only with a fresh installation. Remove your bridge from your idevice. Delete .homebridge/accessories and .homebridge/persist then restart homebridge. Everything should be ok.
