### ISSUE TITLE
Homebridge plugin feedback issue

### ISSUE THREAD

**Issue by erliona** [ilcato/homebridge-Fibaro-HC2#49]
I have a problem with feedback in homekit (homebridge). Concretely, when changing the brightness through fibaro (for example), homekit not recognize in real time that the change occurred. Please advise.

**Comment by ilcato** [comment]
It works for me. Try to give me more details.

**Comment by erliona** [comment]
okay, I configure device at my fibaro-homecenter-2, then install homebridge
and your plugin on raspberry PI 3, and the please see video that I have
record describing this issue https://www.youtube.com/watch?v=WfSVac7pUn0


2017-01-19 18:50 GMT+03:00 ilcato <notifications@github.com>:

**Comment by ilcato** [comment]
The plugin manage the automatic update of homekit with changes coming from home center through a polling mechanism. By default it check updates every 5 seconds, so try to wait at least 5 second to see if the change in home center is propagated to homekit.
You can have a higher update frequency by setting the parameter "pollerperiod" in config.json to a value less than 5.

**Comment by BilboSwagginz** [comment]
#25

**Comment by ilcato** [comment]
@erliona, any feedback?
