### ISSUE TITLE
Danfoss Thermostat

### ISSUE THREAD

**Issue by R-TEMI** [ilcato/homebridge-Fibaro-HC2#50]
Version 1.05 and full rescan of accessories did not help me get the following devices on the list:

{"id":18,"name":"Thermostat Sleeping","roomID":4,"type":"com.fibaro.thermostatDanfoss","baseType":"com.fibaro.hvac","enabled":true,"visible":true,"isPlugin":false,"parentId":17,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["battery","zwave","zwaveProtection","zwaveWakeup"],"properties":{"batteryLevel":80,"pollingTimeSec":0,"wakeUpTime":900,"zwaveCompany":"Danfoss","zwaveInfo":"6,3,67","zwaveVersion":"1.1","RFProtectionState":"0","RFProtectionSupport":"0","batteryLowNotification":"true","configured":"true","dead":"false","defInterval":"0","deviceControlType":"0","deviceIcon":"34","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","liliOffCommand":"","liliOnCommand":"","localProtectionState":"0","localProtectionSupport":"5","log":"","logTemp":"","manufacturer":"","markAsDead":"true","maxInterval":"0","minInterval":"0","model":"","nodeId":"5","parametersTemplate":"322","productInfo":"0,2,0,5,0,4,1,1","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","stepInterval":"0","targetLevel":"20.00","timestamp":"1485875356","unit":"C","useTemplate":"true","userDescription":"","value":"20.00"},"actions":{"reconfigure":0,"setInterval":1,"setTargetLevel":1,"setTime":1},"created":1485113161,"modified":1485113161,"sortOrder":9},{"id":29,"name":"Thermostat Right","roomID":4,"type":"com.fibaro.thermostatDanfoss","baseType":"com.fibaro.hvac","enabled":true,"visible":true,"isPlugin":false,"parentId":28,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["battery","zwave","zwaveProtection","zwaveWakeup"],"properties":{"batteryLevel":55,"pollingTimeSec":0,"wakeUpTime":900,"zwaveCompany":"Danfoss","zwaveInfo":"6,3,67","zwaveVersion":"1.1","RFProtectionState":"0","RFProtectionSupport":"0","batteryLowNotification":"true","configured":"true","dead":"false","defInterval":"0","deviceControlType":"0","deviceIcon":"34","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","liliOffCommand":"","liliOnCommand":"","localProtectionState":"0","localProtectionSupport":"5","log":"","logTemp":"","manufacturer":"","markAsDead":"true","maxInterval":"0","minInterval":"0","model":"","nodeId":"9","parametersTemplate":"322","productInfo":"0,2,0,5,0,4,1,1","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","stepInterval":"0","targetLevel":"20.00","timestamp":"1485875356","unit":"C","useTemplate":"true","userDescription":"","value":"20.00"},"actions":{"reconfigure":0,"setInterval":1,"setTargetLevel":1,"setTime":1},"created":1485113161,"modified":1485113161,"sortOrder":10},{"id":31,"name":"Thermostat Left","roomID":4,"type":"com.fibaro.thermostatDanfoss","baseType":"com.fibaro.hvac","enabled":true,"visible":true,"isPlugin":false,"parentId":30,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["battery","zwave","zwaveProtection","zwaveWakeup"],"properties":{"batteryLevel":41,"pollingTimeSec":0,"wakeUpTime":900,"zwaveCompany":"Danfoss","zwaveInfo":"6,3,67","zwaveVersion":"1.1","RFProtectionState":"0","RFProtectionSupport":"0","batteryLowNotification":"true","configured":"true","dead":"false","defInterval":"0","deviceControlType":"0","deviceIcon":"34","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","liliOffCommand":"","liliOnCommand":"","localProtectionState":"0","localProtectionSupport":"5","log":"","logTemp":"","manufacturer":"","markAsDead":"true","maxInterval":"0","minInterval":"0","model":"","nodeId":"10","parametersTemplate":"322","productInfo":"0,2,0,5,0,4,1,1","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","stepInterval":"0","targetLevel":"20.00","timestamp":"1485875356","unit":"C","useTemplate":"true","userDescription":"","value":"20.00"},"actions":{"reconfigure":0,"setInterval":1,"setTargetLevel":1,"setTime":1},"created":1485113162,"modified":1485113162,"sortOrder":11},{"id":36,"name":"iOS_Temp","roomID":4,"type":"virtual_device","visible":true,"enabled":true,"properties":{"deviceIcon":0,"ip":"10.0.7.2","port":80,"log":"","logTemp":"","currentIcon":"0","log":"","logTemp":"","mainLoop":"","visible":"true","rows":[{"type":"button","elements":[{"id":1,"lua":false,"waitForResponse":true,"caption":"22C","name":"Temp","empty":false,"msg":"GET /api/sceneControl?id=10&action=start HTTP/1.10x0D0x0AHost: 10.0.7.20x0D0x0AAuthorization: Basic cGk6VFh1d2lZQ0ZyemhnaXJZdW9rTjI=0x0D0x0A0x0D0x0A","buttonIcon":0,"favourite":false,"main":true}]}]},"actions":{"pressButton":1,"setSlider":2,"setProperty":2},"created":1485113163,"modified":1485113163,"sortOrder":12}]

**Comment by ilcato** [comment]
@R-TEMI, try the new version 1.0.6 of the plugin.

**Comment by ilcato** [comment]
@R-TEMI any feedback?

**Comment by R-TEMI** [comment]
Works well, thanks!
