### ISSUE TITLE
Light Sensor lux value too high

### ISSUE THREAD

**Issue by BilboSwagginz** [ilcato/homebridge-Fibaro-HC2#51]
Hello, here is another problem with the lux value, if the value is too high it appears as "Not responding" at this exact time it is at around 1500 lux

Sinceraly - Konrad

**Comment by ilcato** [comment]
I set the maximum value to 1000 lux.
Which is the realistic maximum value?

**Comment by BilboSwagginz** [comment]
100k is the max in direct sunligt

**Comment by ilcato** [comment]
I need to limit it to a smaller number. Let's put it 10000 for the moment.

**Comment by BilboSwagginz** [comment]
Okay, fantastkc! Thanks a lot!
