### ISSUE TITLE
Fibaro id

### ISSUE THREAD

**Issue by nrm83** [ilcato/homebridge-Fibaro-HC2#52]
Since updating from fibaro system our plugin no work anymore we have try lot of time to reinstall but no work anymore can you help me

They work since more than 6month but now no work anymore[2017-02-12 23:24:09] [FibaroHC2] Error getting data from Home Center: Error: connect ECONNREFUSED 88.120.38.104:31114 undefined

**Comment by ilcato** [comment]
Are using the right credentials? After last Home Center upgrade it force you to change username.

**Comment by nrm83** [comment]
Yes all is right about credentials I try with need and I create special credentials for home ridge the booth not work, I don't know what happens

**Comment by ilcato** [comment]
are you able to connect to the address http://HC_IP/docs from the homebridge machine?

**Comment by nrm83** [comment]
Wget http://HC_IP/docs no work

But for information we have Netatmo continu to work correctly only fibaro not work.

**Comment by ilcato** [comment]
off course you change HC_IP with the IP address of your home center right ? :-)

**Comment by nrm83** [comment]
I found the solution, we have a redirection on router and we have remade with same parameters now work thank you
