### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Pascal26120** [ilcato/homebridge-Fibaro-HC2#53]
Hi,
Do you think it's posssible to have version of homebridge-fibaro-hc2, who can display all devices in my fibaro HC2 ?
Actualy only fibaro devices are listen on homebrige.
For exemple Domitech Dimm-Leuchte ZBULB LED E27 is not listen on homebridge.

Best regards

**Comment by ilcato** [comment]
it is possible but we need to manage every single device. Pease provide description of it.

**Comment by Pascal26120** [comment]
Find attacnment the manual of Domitech Dimm-Leuchte ZBULB LED E27 - Z-Wave

Regards
[Manual_Domitech_ZBulb.pdf](https://github.com/ilcato/homebridge-Fibaro-HC2/files/774006/Manual_Domitech_ZBulb.pdf)

**Comment by ilcato** [comment]
send me the result of:
`http://HC_IP/api/devices/DEVICE_ID`
where HC_IP is the address of your Home Center and DEVICE_ID is the ID of the ZBULB.

**Comment by Pascal26120** [comment]
Hi,

I'm out ouf my home for few days.
When I'll come back, I try this and send the report.

Thank you for support

Regards

Le 15 févr. 2017 à 18:27, ilcato <notifications@github.com<mailto:notifications@github.com>> a écrit :


send me the result of:
http://HC_IP/api/devices/DEVICE_ID<http://hc_ip/api/devices/DEVICE_ID>
where HC_IP is the address of your Home Center and DEVICE_ID is the ID of the ZBULB.

**Comment by Pascal26120** [comment]
Hi,

See below the result : 
[code]
{"id":51,"name":"Lumière cuisine","roomID":12,"type":"com.fibaro.multilevelSwitch","baseType":"com.fibaro.binarySwitch","enabled":true,"visible":true,"isPlugin":false,"parentId":50,"remoteGatewayId":0,"interfaces":["deviceGrouping","fibaroFirmwareUpdate","levelChange","light","zwave","zwaveSwitchAll"],"properties":{"parameters":[],"pollingTimeSec":0,"zwaveCompany":"","zwaveInfo":"3,4,5","zwaveVersion":"5.14","configured":"true","dead":"false","deviceControlType":"23","deviceGroup":"[]","deviceGroupMaster":"0","deviceIcon":"15","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","firmwareUpdate":"{\"status\":\"UpToDate\",\"updateVersion\":\"\"}","isLight":"true","liliOffCommand":"","liliOnCommand":"","log":"","logTemp":"","manufacturer":"","markAsDead":"true","model":"","nodeId":"10","parametersTemplate":"0","productInfo":"2,14,76,66,49,52,5,14","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"false","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","switchAllMode":"SWITCH_ALL_INCLUDED_IN_THE_ALL_ON_ALL_OFF_FUNCTIONALITY","updateVersion":"","useTemplate":"false","userDescription":"","value":"0"},"actions":{"abortUpdate":1,"reconfigure":0,"retryUpdate":1,"setValue":1,"startLevelDecrease":0,"startLevelIncrease":0,"startUpdate":1,"stopLevelChange":0,"turnOff":0,"turnOn":0,"updateFirmware":1},"created":1487437094,"modified":1487437094,"sortOrder":38}
[/code]
Regards

**Comment by ilcato** [comment]
It's configured as a com.fibaro.multilevelSwitch so it should be included by the plugin. Strange.
Is it a problem of visibility or functioning ?

**Comment by Pascal26120** [comment]
Hi,

Sorry. The problem is not about hombridge, but fibaro hc2 firmware (template missing).
Device well displayed on the plugin.

Thank you for support
