### ISSUE TITLE
Enhancement: Battery Levels

### ISSUE THREAD

**Issue by ryanmaxwell** [ilcato/homebridge-Fibaro-HC2#54]
Hi ilcato,

I haven't looked too deeply into it, but I've read that iOS 10.3 adds support for showing accessory battery levels into the home app.

The `Characteristic.BatteryLevel` has existed in HAP-NodeJS for a while, and the Fibaro api exposes `batteryLevel` as a device property. Fibaro documentation says it is a percentage, but I currently have a flat device that is reporting 255 for the batteryLevel so that should be taken into consideration.

Do you think we can add this to the plugin for the door/window contact sensors, and the motion sensors?

**Comment by ilcato** [comment]
Simulated this but Home app doesn't show battery levels.

**Comment by ryanmaxwell** [comment]
@ilcato Interesting, the release notes for iOS 10.3 states 
> Home app support for accessory battery level status

https://support.apple.com/kb/DL1893?locale=en_US

 Provided we are passing the state information through to homekit correctly it should also be available to siri I thought that's http://www.ilounge.com/index.php/tips/comments/checking-homekit-accessory-battery-levels-with-siri

Otherwise perhaps there may be a fault in homebridge or hap-nodejs?
