### ISSUE TITLE
arming status of devices scenes

### ISSUE THREAD

**Issue by Mx-Razvan** [ilcato/homebridge-Fibaro-HC2#56]
hi @ilcato 

how should the scenes for setting arming status of the devices should look using block scenes (HCL)?

Thanks,

R

**Comment by ilcato** [comment]
set the armed status of each of your sensors to the right one
set the global variable "SecuritySystem" to the right value

simply that

**Comment by Mx-Razvan** [comment]
@ilcato 

I figured it out, thanks @ilcato.
In the fibarosecuritysystem the switch has home, away, night and off. What is the supposed behavior of home?
Also at HomeKit app launch the fibarosecuritysystem appears as armed and trying to disarm but nothing happens. Any idea why?

**Comment by ilcato** [comment]
not shure of the meaning of "home", I configured it the same as night but without arming windows sensors.
Regarding the second issue it should be fixed in version 1.1.1 I published yesterday evening.

**Comment by Mx-Razvan** [comment]
my switch for fibarosecuritysystem has it at first position. I configured it as a forced arm.
The problem with the status update was mine - I replaced the updated files manually and now all is ok.

Thanks for your work!
