### ISSUE TITLE
Ignore certain devices?

### ISSUE THREAD

**Issue by CelticWebSolutions** [ilcato/homebridge-Fibaro-HC2#57]
Hi,

I'm coming to fibaro after having run a Ver for the last year or two.  I've had the vera setup with home bridge for some time now, home bridge has always been pretty stable so devices to add the Fibaro to it using your plugin.

There are a number of devices that I do not wish to use with homebridge, with the vera plugin there is an ignore section for ignoring scenes and / or specific devices.  Is it possible to ignore devices with your plugin too please?

Many thanks for your reply.

**Comment by ilcato** [comment]
@CelticWebSolutions you have 2 options:

1. create a new user in HCL and assign to it the visibility only to the device you want to see from homebridge. Use such a user in the config.json.  Restart homebridge.

1. rename the device that you want to exclude with an _ as the first character. Restart homebridge.

**Comment by CelticWebSolutions** [comment]
Didn't think of the users!  Just made a user specifically for Homebridge and that works perfectly :)

Thank you for the prompt reply.
