### ISSUE TITLE
remotec ac control is not showing in homekit app

### ISSUE THREAD

**Issue by audiocafe123** [ilcato/homebridge-Fibaro-HC2#58]
hi
recently i have installed the homebridge in raspberry pi 3 ,with the fibaro plugin..
im able to see all the devices in homekit except the remotec ac ir extender. ive tried redoing it by seeing your post,but nothing worked out...im new to this platform ,so please guide how to get the ac control device in homekit app.
thanks

**Comment by ilcato** [comment]
I do not have such a device so it's difficult for me to support you.

**Comment by audiocafe123** [comment]
hi ilcato.
yes i have the same device,and im facing the same issue.
do have any solution for this??

**Comment by ilcato** [comment]
@audiocafe123 the other users are now able to see it and use for setting temperature. The issue still open is the ability to change the mode.
