### ISSUE TITLE
Motion Sensor?

### ISSUE THREAD

**Issue by leoneleone** [ilcato/homebridge-Fibaro-HC2#6]
Hi, my Fibaro Motion Sensors are registered by Homebridge but do not appear in my HomeKit config regardless of which app I use.

Once everything is up and running in Homebridge, do fibre devices show up automatically as with other plugins?

Thanks :)

**Comment by ilcato** [comment]
Yes, which other plugins do you use?

**Comment by leoneleone** [comment]
homebridge-dummy
homebridge-harmonyhub
homebridge-wemo
homebridge-sonos
homebridge-sensibo

**Comment by ilcato** [comment]
Do you have other Fibaro devices beside the motion sensor? Do they appear in Homekit?

**Comment by leoneleone** [comment]
still in the process of adding my devices to the Fibaro HCL. Only Motion Sensors really and a couple of Door/Window sensors.

I'll update the plugin and try again once I've finished setting you my HCL

**Comment by leoneleone** [comment]
Ok. So my older Fibaro motion sensors v2.8 are found by the plugin and I can see them in my HomeKit config. Unfortunately my newer Sensors don't show up.

I believe they aren't being discovered because Fibaro changed "com.fibaro.FGMS001" to include a version number. That's why the Plugin doesn't register them.

Is there anyway to change the code in index.js to include sensors with the prefix 'com.fibaro.FGMS001', so that new devices with version numbers after "com.fibaro.FGMS001" are discovered as well?

**Comment by leoneleone** [comment]
the device FingerPrint for the new Fibaro motion sensors has changed slightly. we need to be less strict about  s.type == "com.fibaro.FGMS001" to get the plugin to discover them.

**Comment by ilcato** [comment]
what's the new type?

**Comment by leoneleone** [comment]
its the same basically, with a version number added to the end
"com.fibaro.FGMS001xx" where xx is the version number, but i'm not sure what the form of xx is
been trying to search online but can't find the exact naming.

to safeguard future Fibaro releases, can we no have:
else if (s.type ==**if string includes** "com.fibaro.FGMS001" || s.type == "com.fibaro.motionSensor")? 

I'm not sure what the correct comparison syntax would be.
An "if String.Contains" sort of comparison?

**Comment by ilcato** [comment]
yes.on which platform are you running homebridge?

**Comment by leoneleone** [comment]
Raspberry Pi 2

**Comment by ilcato** [comment]
ok. I just published on github an update on index.js to manage this.
Copy manually it on /usr/local/lib/node_modules/homebridge-fibaro-hc2 and restart homebridge.
If it works I will create a new package on npmjs.

**Comment by leoneleone** [comment]
I added the change to my index.js file and we have lift-off! All my configured Fibaro motion sensors are showing up in HomeKit now.
It could be that all newer Fibaro devices have had similar Fingerprint changes. I'm in the UK and can only speak for EU Fibaro devices. I'll let you know if I discover any. I know that the newer motion sensors have an added Accelerometer device nested within them, the older ones don't.

Thank you so much for your help and quick responses :)
