### ISSUE TITLE
Strange updates from HomeKit

### ISSUE THREAD

**Issue by CelticWebSolutions** [ilcato/homebridge-Fibaro-HC2#62]
Whenever I go in to Home app or pull up the Home favourites form the bottom of the screen, it then updates and starts telling me about doors being opened / closed that have often been open / closed for some time.  Is there a way to stop this behaviour?  I don't get it with any other plugins, just the fibaro home centre one

Thanks in advance for your help :)

**Comment by ilcato** [comment]
Not clear for me what you are saying.

**Comment by CelticWebSolutions** [comment]
Sorry, I'll try to explain a bit more clearly.

When I for example open my gate, the sensor is linked to HomeKit from my fibaro with your plugin.  If I open the gate home doe snot notify me.  But if I then open Home, I get the notification popup when it checks.

So if I've opened my garage, my gates and say my back door at different times, my wife would get a notification for all 3 at the time I open the home app rather than at the time the doors and gates were actually opened.  

When I had Vera Plus and the Vera plugin, these updates were almost instant, have I got something setup incorrectly or is this just how this plugin works?

Thanks for your help :)

**Comment by ilcato** [comment]
@CelticWebSolutions , I had a similar problem some time ago. I disable the notification for the Home app in the setting in iOs. Than rebooted the iPhone. Then enabled the notification.
It was an iOs problem.
Can you try ?

**Comment by CelticWebSolutions** [comment]
Just tried that, I'm afraid it still does not work.  

It appears there are a few of us with the same issue, there are a couple of people on the thread in Fibaro forum with this issue.

Just to let you have some more information, when you first open the Home app, it says updating, it is only then do the devices update with their new statuses and notifications fire.

**Comment by CelticWebSolutions** [comment]
I think I've just fixed it, though I'm not sure how exactly I did it as I did a fe things at once.

I decided to go and check my config file.  Nothing looked out of place but I decided to change the poling time to 1 and then I changed the grouping to "room"

Then I restarted Homebridge.  I've restarted home bridge many times before so it wasn't the restart part that fixed it.

I opened Home and everything had changed and it thought they were all new devices again, so I tested it and all worked correctly and notifications came through when app was closed. I then moved everything to the correct rooms and set my Favourites.  Everything still works!

So I'm not quite sure if it was changing the settings atet was the actual fix, or that when the settings were changed it sort of reset Home app.  Either way.  I believe this is now fixed.  Fingers crossed it stays fixed :)

Thanks for your help!

**Comment by CelticWebSolutions** [comment]
I spoke to soon!  Its' stopped working again.  That said, it was only after I used my My-Q enabled garage door, so it's possible that it was that that caused the issue.  Going to try a reset again now and disable that plugin to see if it's that causing the problem.

**Comment by ilcato** [comment]
I think it is a bug in iOs and some of the things that you made reset something inside the operating system; also in my case. See this issue in [homebridge](https://github.com/nfarina/homebridge/issues/1006).
Please update also the forum with your findings.
Thanks.
