### ISSUE TITLE
Problems Homebridge pluging Fibaro HC2

### ISSUE THREAD

**Issue by MeesHazeleger** [ilcato/homebridge-Fibaro-HC2#65]
I've recently have updated the homebridge because of a pluging problem, now the homebridge is working fine but can't load the FIBARO HC2 plugin. 

***      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
 Error: The requested platform 'Fibaro-HC2' was not registered by any plugin.
at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)

GET https://registry.npmjs.org/homebridge-fibaro-hc2
[0m[37;40mnpm[0m [0m[32minfo[0m [0m[35mretry[0m will retry, error on last attempt: TypeError: The header content contains invalid character***

I'm running homebridge om a docker in Synology

All the help is welcome !

**Comment by ilcato** [comment]
It seems you didn't install the plugin properly. Try again with:

sudo npm install -g homebridge-fibaro-hc2

and share the result of the installation.

**Comment by MeesHazeleger** [comment]
unfortunately, this doesn't solve the problem

Same error as before

**Comment by ilcato** [comment]
Is the plugin correctly installed? Whats the log of the installation procedure?

**Comment by MeesHazeleger** [comment]
[Document1.pdf](https://github.com/ilcato/homebridge-Fibaro-HC2/files/1026061/Document1.pdf)

I've uploaded the log of the terminal

**Comment by MeesHazeleger** [comment]
complete log

**Comment by ilcato** [comment]
I mean the terminal log of the command:

sudo npm install -g homebridge-fibaro-hc2

**Comment by MeesHazeleger** [comment]
I've trieded to install de plug in in the terminal of de docker typing npm install homebridge-fibaro-hc2, that worked well. Then I've rerun the container with the install.sh file and config.json file, run the container and everything is working again. Thanks for your support
