### ISSUE TITLE
how to integrate yale digital and 2n helios to homebridge?

### ISSUE THREAD

**Issue by audiocafe123** [ilcato/homebridge-Fibaro-HC2#66]
hi..
i have few question . please help me solving .

1.is  any plugin, what i have installed in fibaro, will that be updated to homebridge??
2.im looking for configuring the 2n helios vdp to homebridge, either through direct plugin or through fibaro.
3.is there any plugins for yale lock ,so that i can configure with homebridge.

thanks in advance

**Comment by ilcato** [comment]
1. I do not understand the question
2. I don't know
3. if you are using the Yale Lock through Fibaro it should be exposed to homebridge via my plugin.

**Comment by audiocafe123** [comment]
2n Helios Plugin is not showing in our home-kit.
But its working through Fibaro HC2, is there any extra plugin to add homebridge. we are tried lot of times but its not showing in our home-kit....

**Comment by ilcato** [comment]
It's not supported through my plugin.

**Comment by audiocafe123** [comment]
have to configure 2N to homebridge, you have any particular plugin for homebridge, we need your suggestion ...

**Comment by ilcato** [comment]
no

**Comment by audiocafe123** [comment]
then how to configure 2n to homebridge... pls suggest me.....

**Comment by ilcato** [comment]
no idea. I do not have such a product.

**Comment by audiocafe123** [comment]
How to configure 2N Helios video door phone to homebridge...
