### ISSUE TITLE
Accessory types

### ISSUE THREAD

**Issue by Batoon69** [ilcato/homebridge-Fibaro-HC2#7]
Good evening Ilcato,
Using homebridge-Fibaro-hc2 plugin, some "lighting" accessories are transformed in "power" accessories. This is the case for modules as FGS switches or Fibaro Wall plugs. The issue is that these accessories are not recognized when you ask Siri to switch on the lights. Of course you can fix it manually using eve for instance. But would it be possible to make them automatically recognized as lighting accessories buy homekit ? (As they are defined as lighting in hc2 interface). Thanks. Sébastien.

**Comment by ilcato** [comment]
Yes, it is possible and it is one of the feature I'm adding to the iOs app, the same that allows to import rooms and zones.
Unfortunately it is not possible to manage it from the homebridge plugin.

**Comment by Batoon69** [comment]
Great! When do you think this functionality will be available in your ios app?

**Comment by ilcato** [comment]
a few weeks, I have a lot of backlog and additionally in this case Apple needs time for app approval.

**Comment by ilcato** [comment]
@Batoon69: fixed with @ryanmaxwell solution
