### ISSUE TITLE
Security System update

### ISSUE THREAD

**Issue by Ti-Bo** [ilcato/homebridge-Fibaro-HC2#74]
Hi !
Thanks for this great plugin 👍 

I have an issue with security system update in background only. When I open Home, the security system state update correctly but seems it never update in background as the other modules. 

Thank you  :)

**Comment by ilcato** [comment]
will check it

**Comment by darrenmcuk** [comment]
yer I have seen that as well

**Comment by ilcato** [comment]
Version 2.1.4 should fix the issue. @Ti-Bo, @darrenmcuk can you check?

**Comment by ilcato** [comment]
In my installation with the new version it works.

**Comment by ilcato** [comment]
Did you update the plugin and restarted it?

**Comment by Ti-Bo** [comment]
Yes I updated it and restarted the Raspberry. I’ve updated Homebridge too.

**Comment by ilcato** [comment]
Are you sure that the latest version is the one installed? Sometimes it doesn't upgrade.

**Comment by Ti-Bo** [comment]
The version displayed is 2.1.5... I tried a new installation and I’ve the same bug :/
