### ISSUE TITLE
Lock - Danalock

### ISSUE THREAD

**Issue by issic** [ilcato/homebridge-Fibaro-HC2#79]
Hey iLcato, awesome plugin, works like a charm. In version .66 you write Added support for Door Locks (tested on Danalock and Yale devices).

But my Danalock V3 can't show in Homebridge. It's in Fibaro HC2 and working, but not in Homebridge. Any idea how to work it out?

**Comment by ilcato** [comment]
I do not have such a device, other users said it works. Can you send me your homebridge log at the startup?

**Comment by issic** [comment]
Sort it out, sorry for the issue. I'm using different user to access Fibaro, then I can control which device you have access to. I added lock and few others recently and didn't allowed this user "homebridge" to access to them. Works like a charm.

(that would be a good Wiki part how to limit access to devices you don't want to have in HomeKit)

I have question about the SecuritySystem. What is HomeKit sending to Fibaro? Who's changing the global variable and how. Or HomeKit call for scene and scene change the variable? It's bit unclear.

**Comment by ilcato** [comment]
The second one.
