### ISSUE TITLE
Yale Smart Lock

### ISSUE THREAD

**Issue by simonrb2000** [ilcato/homebridge-Fibaro-HC2#8]
Hi Ilcato

Thinking of buying one of these. http://www.yale.co.uk/en/yale/couk/productsdb/smart-locks/Keyfree-Connected-Smart-Lock/

Would I need the ZWave module for it to use your homebridge plugin? Currently I use domoticz to control most things. I haven't got ZWave setup in the house just yer but will If I can get my doors to lock and unlock using it. 

Thank you :)

**Comment by ilcato** [comment]
If you want to use homekit with domoticz you need to install the corresponding homebridge plugin: https://www.npmjs.com/package/homebridge-edomoticz.
It doesn't support smart locks as of today.
With my Fibaro plugin you will be able to use the Yale Smart Lock but you also need to buy a Fibaro Home Center controller and the z-wave module of Yale.

**Comment by simonrb2000** [comment]
Thanks for quick reply. I currently use homebridge and domoticz together and works well. Just wanted to add the front door to it. So I would have to buy a Fibaro Home Centre Controller and ZWave... I'll get googling :)

Thank you

**Comment by ilcato** [comment]
Or ask the developer of the domoticz plugin to support smart locks ...

**Comment by simonrb2000** [comment]
I think its domoticz that doesn't support the yale smart lock
