### ISSUE TITLE
More than 100 devices

### ISSUE THREAD

**Issue by beorn** [ilcato/homebridge-Fibaro-HC2#80]
Hi, iOS has a limit of 100 accessories per device (=bridge), so that makes it impossible to use this for a semi-large Fibaro installation - see https://github.com/nfarina/homebridge/issues/827#issuecomment-251146385

It would be great to have a way to hide some devices, or partition the accessories into multiple bridges (by type, id hash, or something), to allow larger installations to be bridged into Homebridge.

**Comment by ilcato** [comment]
Create a Fibaro user with the limited visibility on the device you want to add to Homebridge and use such a user with corresponding credentials in configure.json

**Comment by beorn** [comment]
Ah, that works!  Thanks! :)

**Comment by ilcato** [comment]
ok
