### ISSUE TITLE
Losing state upon exception

### ISSUE THREAD

**Issue by beorn** [ilcato/homebridge-Fibaro-HC2#82]
Hi,

  It works, but whenever I restart homebridge a lot of the state is lost - room, favorites - all the devices show up in the default room without any state/ name changed preserved.

After some google'ing it seems one potential problem could be if the plugin doesn't support the 'new API':

https://github.com/nfarina/homebridge/issues/874
https://github.com/pdlove/homebridge-smartthings/issues/158
https://github.com/nfarina/homebridge/issues/1005

and fail sometimes to return all devices (accessories and services), or fail with an exception.  The exception I'm running into is: https://github.com/ilcato/homebridge-Fibaro-HC2/issues/81

**Comment by ilcato** [comment]
The plugin is supporting the new API.

**Comment by beorn** [comment]
The issue is when there's an exception, like described in #81, all state is lost.
