### ISSUE TITLE
Don't crash when accessory is not available

### ISSUE THREAD

**Issue by iRonin** [ilcato/homebridge-Fibaro-HC2#83]
There is an exception thrown (and not caught/handled properly) whenever there is a change of state when an accessory is not available. I've got floor heating thermostats configured but most of the time floor heating breakers are off so the thermostats are offline too; I do have them present in certain scenes I want still to be run.

**Comment by ilcato** [comment]
Please explain the issue better

**Comment by ilcato** [comment]
Any news?

**Comment by iRonin** [comment]
I was unable to reproduce it.
