### ISSUE TITLE
don't work anymore with other device

### ISSUE THREAD

**Issue by alessandrocialente** [ilcato/homebridge-Fibaro-HC2#84]
hi ,
i have i new iPhone X with ios11.2.2 , fiber hc2 with 90 items, today after i invite my wife that have iPhone 7 at using the app home, don't work anymore. 
i just have this problem with iOS 11 b and clean all and reinstall app changed pin number but now don't work.
can you help me please ?

**Comment by alessandrocialente** [comment]
when i insert the pin 031-45.-166 that i have change, the app search  home bridge but don't found it.

**Comment by ilcato** [comment]
Which exact version of iOS do you have?

**Comment by ilcato** [comment]
Any news?
