### ISSUE TITLE
Aeotec Garage Door Controller

### ISSUE THREAD

**Issue by lhusoey** [ilcato/homebridge-Fibaro-HC2#87]
Hi,

I`m having problems with my aeotec garage door controller.
In HC2 it works fine. But it is not showing up in homebridge.
Is there no support for this?
Have tried to delete accessories folder and restarted homebridge.

Hombridge is installed in rasberrypi 3

**Comment by ilcato** [comment]
I released 6h ago version 2.0.8 of the plugin that support Aeotec GDC. Are you sure to be on the latest version?

**Comment by lhusoey** [comment]
Hi,, thanks for the reply :)

No i am not on the latest version. Do i need to unistall current version before installing the new one?
If so, how do i uninstall? neewbie to raspberry/linux

**Comment by ilcato** [comment]
Install again the plugin over the previous one.
