### ISSUE TITLE
Popp smoke detector/wireless alarm

### ISSUE THREAD

**Issue by Andreasjohansen** [ilcato/homebridge-Fibaro-HC2#88]
Could you add support for this?

**Comment by ilcato** [comment]
Send me the json data please.

**Comment by Andreasjohansen** [comment]
{
  "id": 393,
  "name": "Røykvarsler",
  "roomID": 4,
  "type": "com.fibaro.smokeSensor",
  "baseType": "com.fibaro.gasDetector",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 392,
  "remoteGatewayId": 0,
  "interfaces": [
    "battery",
    "fibaroBreach",
    "zwave",
    "zwaveAlarm"
  ],
  "properties": {
    "parameters": [
      {
        "id": 1,
        "lastReportedValue": 10,
        "lastSetValue": 10,
        "size": 1,
        "value": 10
      },
      {
        "id": 2,
        "lastReportedValue": 8,
        "lastSetValue": 8,
        "size": 1,
        "value": 8
      },
      {
        "id": 3,
        "lastReportedValue": 255,
        "lastSetValue": 255,
        "size": 1,
        "value": 255
      },
      {
        "id": 4,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 5,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 6,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      }
    ],
    "pollingTimeSec": 0,
    "zwaveCompany": "Popp & Co",
    "zwaveInfo": "6,4,5",
    "zwaveVersion": "2.1",
    "alarmLevel": "0",
    "alarmType": "0",
    "batteryLevel": "100",
    "batteryLowNotification": "true",
    "configured": false,
    "dead": "false",
    "defInterval": "0",
    "deviceControlType": "0",
    "deviceIcon": "46",
    "emailNotificationID": "0",
    "emailNotificationType": "0",
    "endPointId": "0",
    "lastBreached": "0",
    "liliOffCommand": "",
    "liliOnCommand": "",
    "log": "Not configured",
    "logTemp": "TxtBlue",
    "manufacturer": "",
    "markAsDead": "true",
    "maxInterval": "0",
    "minInterval": "0",
    "model": "",
    "nodeId": "83",
    "parametersTemplate": "0",
    "productInfo": "1,84,1,0,2,1,2,1",
    "pushNotificationID": "0",
    "pushNotificationType": "0",
    "remoteGatewayId": "0",
    "saveLogs": "true",
    "serialNumber": "h'271001f40a5c016b0001ffff",
    "smsNotificationID": "0",
    "smsNotificationType": "0",
    "stepInterval": "0",
    "useTemplate": "false",
    "userDescription": "",
    "value": "false"
  },
  "actions": {
    "forceArm": 0,
    "meetArmConditions": 0,
    "reconfigure": 0,
    "setArmed": 1,
    "setInterval": 1
  },
  "created": 1517241996,
  "modified": 1517241996,
  "sortOrder": 252
}

**Comment by Andreasjohansen** [comment]
{
  "id": 394,
  "name": "Brannvarsler",
  "roomID": 4,
  "type": "com.fibaro.smokeSensor",
  "baseType": "com.fibaro.gasDetector",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 392,
  "remoteGatewayId": 0,
  "interfaces": [
    "battery",
    "fibaroBreach",
    "zwave"
  ],
  "properties": {
    "parameters": [
      {
        "id": 1,
        "lastReportedValue": 10,
        "lastSetValue": 10,
        "size": 1,
        "value": 10
      },
      {
        "id": 2,
        "lastReportedValue": 8,
        "lastSetValue": 8,
        "size": 1,
        "value": 8
      },
      {
        "id": 3,
        "lastReportedValue": 255,
        "lastSetValue": 255,
        "size": 1,
        "value": 255
      },
      {
        "id": 4,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 5,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 6,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      }
    ],
    "pollingTimeSec": 0,
    "zwaveCompany": "Popp & Co",
    "zwaveInfo": "6,4,5",
    "zwaveVersion": "2.1",
    "batteryLevel": "100",
    "batteryLowNotification": "true",
    "configured": false,
    "dead": "false",
    "defInterval": "0",
    "deviceControlType": "0",
    "deviceIcon": "46",
    "emailNotificationID": "0",
    "emailNotificationType": "0",
    "endPointId": "0",
    "lastBreached": "0",
    "liliOffCommand": "",
    "liliOnCommand": "",
    "log": "Not configured",
    "logTemp": "TxtBlue",
    "manufacturer": "",
    "markAsDead": "true",
    "maxInterval": "0",
    "minInterval": "0",
    "model": "",
    "nodeId": "83",
    "parametersTemplate": "0",
    "productInfo": "1,84,1,0,2,1,2,1",
    "pushNotificationID": "0",
    "pushNotificationType": "0",
    "remoteGatewayId": "0",
    "saveLogs": "true",
    "serialNumber": "h'271001f40a5c016b0001ffff",
    "smsNotificationID": "0",
    "smsNotificationType": "0",
    "stepInterval": "0",
    "useTemplate": "false",
    "userDescription": "",
    "value": "false"
  },
  "actions": {
    "forceArm": 0,
    "meetArmConditions": 0,
    "reconfigure": 0,
    "setArmed": 1,
    "setInterval": 1
  },
  "created": 1517241996,
  "modified": 1517241996,
  "sortOrder": 253
}

**Comment by Andreasjohansen** [comment]
Do you need it from the parent-ID also?

**Comment by Andreasjohansen** [comment]
{
  "id": 392,
  "name": "Sirene",
  "roomID": 4,
  "type": "com.fibaro.zwaveDevice",
  "baseType": "com.fibaro.device",
  "enabled": true,
  "visible": true,
  "isPlugin": false,
  "parentId": 1,
  "remoteGatewayId": 0,
  "interfaces": [
    "battery",
    "zwave",
    "zwaveAssociation",
    "zwaveConfiguration",
    "zwaveSecurity",
    "zwaveSlaveRouting"
  ],
  "properties": {
    "associations": "[{\"endPointId\":0,\"groups\":[{\"groupInfo\":{\"commands\":[{\"command\":\"Battery Report\",\"commandClass\":\"Command Class Battery\"},{\"command\":\"Device Reset Locally Notification\",\"commandClass\":\"Command Class Device Reset Locally\"},{\"command\":\"Sensor Binary Report\",\"commandClass\":\"Command Class Sensor Binary\"},{\"command\":\"Notification Report\",\"commandClass\":\"Command Class Notification\"},{\"command\":\"Switch Binary Report\",\"commandClass\":\"Command Class Switch Binary\"}],\"name\":\"Lifeline\",\"profile\":\"General: Lifeline\"},\"id\":1,\"singleChannel\":{\"max\":4,\"set\":[1],\"view\":[1]}},{\"groupInfo\":{\"commands\":[{\"command\":\"Notification Report\",\"commandClass\":\"Command Class Notification\"}],\"name\":\"\",\"profile\":\"Notification: Smoke Alarm\"},\"id\":2,\"singleChannel\":{\"max\":4,\"set\":[],\"view\":[]}},{\"groupInfo\":{\"commands\":[{\"command\":\"Basic Set\",\"commandClass\":\"Command Class Basic\"}],\"name\":\"\",\"profile\":\"Notification: Smoke Alarm\"},\"id\":3,\"singleChannel\":{\"max\":4,\"set\":[],\"view\":[]}}]}]",
    "batteryLevel": "100",
    "batteryLowNotification": "true",
    "configured": false,
    "dead": "false",
    "defInterval": "0",
    "deviceControlType": "0",
    "deviceIcon": "28",
    "deviceSpecificData": "h'271001f40a5c016b0001ffff",
    "deviceSpecificIdType": "Serial Number",
    "deviceState": "NotConfigured",
    "emailNotificationID": "0",
    "emailNotificationType": "0",
    "endPointId": "0",
    "liliOffCommand": "",
    "liliOnCommand": "",
    "log": "Not configured",
    "logTemp": "TxtBlue",
    "manufacturer": "",
    "markAsDead": "true",
    "maxInterval": "0",
    "minInterval": "0",
    "model": "",
    "nodeId": "83",
    "parameters": [
      {
        "id": 1,
        "lastReportedValue": 10,
        "lastSetValue": 10,
        "size": 1,
        "value": 10
      },
      {
        "id": 2,
        "lastReportedValue": 8,
        "lastSetValue": 8,
        "size": 1,
        "value": 8
      },
      {
        "id": 3,
        "lastReportedValue": 255,
        "lastSetValue": 255,
        "size": 1,
        "value": 255
      },
      {
        "id": 4,
        "lastReportedValue": 0,
        "lastSetValue": 0,
        "size": 1,
        "value": 0
      },
      {
        "id": 5,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      },
      {
        "id": 6,
        "lastReportedValue": 1,
        "lastSetValue": 1,
        "size": 1,
        "value": 1
      }
    ],
    "parametersTemplate": "0",
    "pollingTimeSec": 0,
    "productInfo": "1,84,1,0,2,1,2,1",
    "pushNotificationID": "0",
    "pushNotificationType": "0",
    "remoteGatewayId": "0",
    "saveLogs": "true",
    "securitySchemes": "[\"Security0\"]",
    "serialNumber": "h'271001f40a5c016b0001ffff",
    "smsNotificationID": "0",
    "smsNotificationType": "0",
    "stepInterval": "0",
    "useTemplate": "false",
    "userDescription": "",
    "zwaveCompany": "Popp & Co",
    "zwaveInfo": "6,4,5",
    "zwaveSoftwareVersion": "{}",
    "zwaveVersion": "2.1"
  },
  "actions": {
    "getParameter": 1,
    "reconfigure": 0,
    "setInterval": 1,
    "setParameter": 2
  },
  "created": 1517241996,
  "modified": 1517241996,
  "sortOrder": 251
}

**Comment by Andreasjohansen** [comment]
![07bd926e-0a9f-4a81-98e7-c21c92c03941](https://user-images.githubusercontent.com/35890467/35596659-0def52e6-061b-11e8-8423-4ab6bdc61eac.png)

**Comment by ilcato** [comment]
Can you test it after copying dist/shadows.js file?

**Comment by Andreasjohansen** [comment]
I will, later today :)

**Comment by Andreasjohansen** [comment]
All smoke detectors ends up in my kitchen

**Comment by ilcato** [comment]
?

**Comment by Andreasjohansen** [comment]
All added smoke-devices is automatic grouped to the kitchen.

**Comment by ilcato** [comment]
Aren't them? I see in your snapshot that they all belong to stue.

**Comment by Andreasjohansen** [comment]
those two branches belongs «stue», And «stue» means living room. Not kitchen. I have total 5 of those smoke detectors. In 5 different rooms:) when added to HomeKit, i should Get 10 new devices total.

**Comment by ilcato** [comment]
Probably Stue is your default room. The plugin doesn't associate a room to the device. I developed an iOs app that allow for the import and association of room and devices. But I stopped developing it and it is no more present in the App Store. Assign manually the room to the accessories. Do they work?

**Comment by Andreasjohansen** [comment]
Maybe. All the other devices ended up in a room called standard. Will try in a few hours.

**Comment by Andreasjohansen** [comment]
IT works, but Every device i test says its detected smoke in the living room. Even If they are assigned to different rooms.

**Comment by ilcato** [comment]
any news?
