### ISSUE TITLE
Security system

### ISSUE THREAD

**Issue by Lesix69** [ilcato/homebridge-Fibaro-HC2#94]
I've configured HC2 plugin with option "securitysystem": "enabled". I've got integration on Fibaro HC2 with alarm system Satel Integra which works fine on Fibaro side. However in Homebridge I'm receiving an error when this option is enabled:
There was a problem getting value from Global Variable: SecuritySystem  - Err: null 

Alarm system is visible in Apple Home app but when trying to change the state there is a message that it is trying to arm or disarm alarm system but with no success.
Could you provide more info how that integration should work and how it should be configured? For instance how to define partitions to be armed/disarmed for Out of home, In home, Night options visible in Apple Home app?

Thanks,

**Comment by ilcato** [comment]
The documentation of the future is in the [wiki](https://github.com/ilcato/homebridge-Fibaro-HC2/wiki/Fibaro-Security-System-configuration-for-HomeKit).

**Comment by Lesix69** [comment]
Thanks a lot!
Sorry, I missed that instruction, now it works perfectly!
