### ISSUE TITLE
Can I Use the Fibaro Plugin Aeotec Z-wave Stick (and without HC2)?

### ISSUE THREAD

**Issue by bjornand1** [ilcato/homebridge-Fibaro-HC2#98]
Hi, I don't have an HC2, but am looking into using the Fibaro Roller Shutter 2 to control my blinds through Homebridge. Does this plugin only work with HC2 or can I get a Aeotec Z-wave stick to act as the Z-wave control center?

**Comment by ilcato** [comment]
This plugin is only for Fibaro Home Center 2 or Home Center Lite.
You can use your z-wave stick and Roller shutters with other controllers like Domoticz or openHAB and use the corresponding plugin for homebridge.
